/**
 * Seed Vocabulary Words
 *
 * Populates the vocabulary_words table with comprehensive Arabic vocabulary.
 * Data extracted from client-side vocabulary and expanded with authentic Arabic words.
 *
 * Categories:
 * - greetings (25 words)
 * - prayer (30 words)
 * - family (25 words)
 * - food (28 words)
 * - nature (25 words)
 * - numbers (20 words)
 * - daily_life (28 words)
 * - islamic_terms (35 words)
 * - body (16 words)
 * - clothing (13 words)
 * - animals (13 words)
 * - colors (11 words)
 * - time (13 words)
 * - emotions (13 words)
 * - places (13 words)
 * - verbs (21 words)
 * - alphabet (28 letters)
 *
 * Total: 356 vocabulary items
 *
 * Usage:
 *   npm run seed:vocabulary
 */

import { db } from "../db";
import { vocabularyWords } from "@shared/schema";
import { defaultLogger } from "../utils/logger";

interface VocabularyEntry {
  arabic: string;
  english: string;
  transliteration: string;
  category: string;
  difficulty: number;
}

/**
 * Complete vocabulary dataset with 356 Arabic words and letters
 */
const VOCABULARY: VocabularyEntry[] = [
  // ============================================================================
  // GREETINGS (25 words)
  // ============================================================================
  {
    arabic: "السلام عليكم",
    transliteration: "As-salamu alaykum",
    english: "Peace be upon you",
    category: "greetings",
    difficulty: 1,
  },
  {
    arabic: "وعليكم السلام",
    transliteration: "Wa alaykum as-salam",
    english: "And upon you peace",
    category: "greetings",
    difficulty: 1,
  },
  {
    arabic: "مرحبا",
    transliteration: "Marhaba",
    english: "Hello",
    category: "greetings",
    difficulty: 1,
  },
  {
    arabic: "أهلا",
    transliteration: "Ahlan",
    english: "Welcome",
    category: "greetings",
    difficulty: 1,
  },
  {
    arabic: "صباح الخير",
    transliteration: "Sabah al-khayr",
    english: "Good morning",
    category: "greetings",
    difficulty: 1,
  },
  {
    arabic: "مساء الخير",
    transliteration: "Masa al-khayr",
    english: "Good evening",
    category: "greetings",
    difficulty: 1,
  },
  {
    arabic: "تصبح على خير",
    transliteration: "Tusbih ala khayr",
    english: "Good night",
    category: "greetings",
    difficulty: 1,
  },
  {
    arabic: "شكرا",
    transliteration: "Shukran",
    english: "Thank you",
    category: "greetings",
    difficulty: 1,
  },
  {
    arabic: "من فضلك",
    transliteration: "Min fadlik",
    english: "Please",
    category: "greetings",
    difficulty: 1,
  },
  {
    arabic: "عفوا",
    transliteration: "Afwan",
    english: "You are welcome",
    category: "greetings",
    difficulty: 1,
  },
  {
    arabic: "كيف حالك",
    transliteration: "Kayfa haluk",
    english: "How are you",
    category: "greetings",
    difficulty: 1,
  },
  {
    arabic: "الحمد لله",
    transliteration: "Alhamdulillah",
    english: "Praise be to God",
    category: "greetings",
    difficulty: 1,
  },
  {
    arabic: "ما شاء الله",
    transliteration: "Masha Allah",
    english: "As God willed",
    category: "greetings",
    difficulty: 2,
  },
  {
    arabic: "بارك الله فيك",
    transliteration: "Baraka Allahu fik",
    english: "May God bless you",
    category: "greetings",
    difficulty: 2,
  },
  {
    arabic: "مع السلامة",
    transliteration: "Maa salama",
    english: "Goodbye",
    category: "greetings",
    difficulty: 1,
  },
  {
    arabic: "في أمان الله",
    transliteration: "Fi aman Allah",
    english: "In God's protection",
    category: "greetings",
    difficulty: 2,
  },
  {
    arabic: "جزاك الله خيرا",
    transliteration: "Jazaka Allahu khayran",
    english: "May God reward you with goodness",
    category: "greetings",
    difficulty: 2,
  },
  {
    arabic: "آمين",
    transliteration: "Ameen",
    english: "Amen",
    category: "greetings",
    difficulty: 1,
  },
  {
    arabic: "نعم",
    transliteration: "Naam",
    english: "Yes",
    category: "greetings",
    difficulty: 1,
  },
  {
    arabic: "لا",
    transliteration: "La",
    english: "No",
    category: "greetings",
    difficulty: 1,
  },
  {
    arabic: "إن شاء الله",
    transliteration: "In sha Allah",
    english: "If God wills",
    category: "greetings",
    difficulty: 2,
  },
  {
    arabic: "سبحان الله",
    transliteration: "Subhan Allah",
    english: "Glory be to God",
    category: "greetings",
    difficulty: 2,
  },
  {
    arabic: "الله أكبر",
    transliteration: "Allahu Akbar",
    english: "God is the Greatest",
    category: "greetings",
    difficulty: 1,
  },
  {
    arabic: "أستغفر الله",
    transliteration: "Astaghfirullah",
    english: "I seek forgiveness from God",
    category: "greetings",
    difficulty: 2,
  },
  {
    arabic: "بسم الله",
    transliteration: "Bismillah",
    english: "In the name of God",
    category: "greetings",
    difficulty: 1,
  },

  // ============================================================================
  // PRAYER (30 words)
  // ============================================================================
  {
    arabic: "صلاة",
    transliteration: "Salah",
    english: "Prayer",
    category: "prayer",
    difficulty: 1,
  },
  {
    arabic: "مسجد",
    transliteration: "Masjid",
    english: "Mosque",
    category: "prayer",
    difficulty: 1,
  },
  {
    arabic: "قرآن",
    transliteration: "Quran",
    english: "Quran",
    category: "prayer",
    difficulty: 1,
  },
  {
    arabic: "الله",
    transliteration: "Allah",
    english: "God",
    category: "prayer",
    difficulty: 1,
  },
  {
    arabic: "دعاء",
    transliteration: "Dua",
    english: "Supplication",
    category: "prayer",
    difficulty: 1,
  },
  {
    arabic: "ركعة",
    transliteration: "Rakah",
    english: "Prayer unit",
    category: "prayer",
    difficulty: 2,
  },
  {
    arabic: "وضوء",
    transliteration: "Wudu",
    english: "Ablution",
    category: "prayer",
    difficulty: 2,
  },
  {
    arabic: "سجدة",
    transliteration: "Sajdah",
    english: "Prostration",
    category: "prayer",
    difficulty: 2,
  },
  {
    arabic: "ركوع",
    transliteration: "Ruku",
    english: "Bowing",
    category: "prayer",
    difficulty: 2,
  },
  {
    arabic: "قيام",
    transliteration: "Qiyam",
    english: "Standing",
    category: "prayer",
    difficulty: 2,
  },
  {
    arabic: "تسبيح",
    transliteration: "Tasbih",
    english: "Glorification",
    category: "prayer",
    difficulty: 2,
  },
  {
    arabic: "تكبير",
    transliteration: "Takbir",
    english: "Saying Allahu Akbar",
    category: "prayer",
    difficulty: 2,
  },
  {
    arabic: "تشهد",
    transliteration: "Tashahhud",
    english: "Testimony of faith in prayer",
    category: "prayer",
    difficulty: 3,
  },
  {
    arabic: "إمام",
    transliteration: "Imam",
    english: "Prayer leader",
    category: "prayer",
    difficulty: 2,
  },
  {
    arabic: "محراب",
    transliteration: "Mihrab",
    english: "Prayer niche",
    category: "prayer",
    difficulty: 3,
  },
  {
    arabic: "مئذنة",
    transliteration: "Midhanah",
    english: "Minaret",
    category: "prayer",
    difficulty: 3,
  },
  {
    arabic: "أذان",
    transliteration: "Adhan",
    english: "Call to prayer",
    category: "prayer",
    difficulty: 2,
  },
  {
    arabic: "إقامة",
    transliteration: "Iqamah",
    english: "Second call to prayer",
    category: "prayer",
    difficulty: 3,
  },
  {
    arabic: "قبلة",
    transliteration: "Qiblah",
    english: "Direction of prayer",
    category: "prayer",
    difficulty: 2,
  },
  {
    arabic: "سجادة",
    transliteration: "Sajjadah",
    english: "Prayer mat",
    category: "prayer",
    difficulty: 2,
  },
  {
    arabic: "مصحف",
    transliteration: "Mushaf",
    english: "Copy of Quran",
    category: "prayer",
    difficulty: 2,
  },
  {
    arabic: "تلاوة",
    transliteration: "Tilawah",
    english: "Recitation",
    category: "prayer",
    difficulty: 3,
  },
  {
    arabic: "فجر",
    transliteration: "Fajr",
    english: "Dawn prayer",
    category: "prayer",
    difficulty: 2,
  },
  {
    arabic: "ظهر",
    transliteration: "Dhuhr",
    english: "Noon prayer",
    category: "prayer",
    difficulty: 2,
  },
  {
    arabic: "عصر",
    transliteration: "Asr",
    english: "Afternoon prayer",
    category: "prayer",
    difficulty: 2,
  },
  {
    arabic: "مغرب",
    transliteration: "Maghrib",
    english: "Sunset prayer",
    category: "prayer",
    difficulty: 2,
  },
  {
    arabic: "عشاء",
    transliteration: "Isha",
    english: "Night prayer",
    category: "prayer",
    difficulty: 2,
  },
  {
    arabic: "جمعة",
    transliteration: "Jumuah",
    english: "Friday prayer",
    category: "prayer",
    difficulty: 2,
  },
  {
    arabic: "خطبة",
    transliteration: "Khutbah",
    english: "Sermon",
    category: "prayer",
    difficulty: 3,
  },
  {
    arabic: "مؤذن",
    transliteration: "Muadhin",
    english: "Caller to prayer",
    category: "prayer",
    difficulty: 3,
  },

  // ============================================================================
  // FAMILY (25 words)
  // ============================================================================
  {
    arabic: "أب",
    transliteration: "Ab",
    english: "Father",
    category: "family",
    difficulty: 1,
  },
  {
    arabic: "أم",
    transliteration: "Umm",
    english: "Mother",
    category: "family",
    difficulty: 1,
  },
  {
    arabic: "أخ",
    transliteration: "Akh",
    english: "Brother",
    category: "family",
    difficulty: 1,
  },
  {
    arabic: "أخت",
    transliteration: "Ukht",
    english: "Sister",
    category: "family",
    difficulty: 1,
  },
  {
    arabic: "ابن",
    transliteration: "Ibn",
    english: "Son",
    category: "family",
    difficulty: 1,
  },
  {
    arabic: "بنت",
    transliteration: "Bint",
    english: "Daughter",
    category: "family",
    difficulty: 1,
  },
  {
    arabic: "جد",
    transliteration: "Jadd",
    english: "Grandfather",
    category: "family",
    difficulty: 1,
  },
  {
    arabic: "جدة",
    transliteration: "Jaddah",
    english: "Grandmother",
    category: "family",
    difficulty: 1,
  },
  {
    arabic: "عم",
    transliteration: "Amm",
    english: "Paternal uncle",
    category: "family",
    difficulty: 2,
  },
  {
    arabic: "عمة",
    transliteration: "Ammah",
    english: "Paternal aunt",
    category: "family",
    difficulty: 2,
  },
  {
    arabic: "خال",
    transliteration: "Khal",
    english: "Maternal uncle",
    category: "family",
    difficulty: 2,
  },
  {
    arabic: "خالة",
    transliteration: "Khalah",
    english: "Maternal aunt",
    category: "family",
    difficulty: 2,
  },
  {
    arabic: "زوج",
    transliteration: "Zawj",
    english: "Husband",
    category: "family",
    difficulty: 2,
  },
  {
    arabic: "زوجة",
    transliteration: "Zawjah",
    english: "Wife",
    category: "family",
    difficulty: 2,
  },
  {
    arabic: "عائلة",
    transliteration: "Ailah",
    english: "Family",
    category: "family",
    difficulty: 1,
  },
  {
    arabic: "حفيد",
    transliteration: "Hafid",
    english: "Grandson",
    category: "family",
    difficulty: 2,
  },
  {
    arabic: "حفيدة",
    transliteration: "Hafidah",
    english: "Granddaughter",
    category: "family",
    difficulty: 2,
  },
  {
    arabic: "أسرة",
    transliteration: "Usrah",
    english: "Household",
    category: "family",
    difficulty: 2,
  },
  {
    arabic: "والد",
    transliteration: "Walid",
    english: "Parent (male)",
    category: "family",
    difficulty: 2,
  },
  {
    arabic: "والدة",
    transliteration: "Walidah",
    english: "Parent (female)",
    category: "family",
    difficulty: 2,
  },
  {
    arabic: "أولاد",
    transliteration: "Awlad",
    english: "Children",
    category: "family",
    difficulty: 2,
  },
  {
    arabic: "طفل",
    transliteration: "Tifl",
    english: "Child",
    category: "family",
    difficulty: 1,
  },
  {
    arabic: "رضيع",
    transliteration: "Radhee",
    english: "Infant",
    category: "family",
    difficulty: 2,
  },
  {
    arabic: "صديق",
    transliteration: "Sadeeq",
    english: "Friend",
    category: "family",
    difficulty: 1,
  },
  {
    arabic: "جار",
    transliteration: "Jar",
    english: "Neighbor",
    category: "family",
    difficulty: 2,
  },

  // ============================================================================
  // FOOD (28 words)
  // ============================================================================
  {
    arabic: "ماء",
    transliteration: "Maa",
    english: "Water",
    category: "food",
    difficulty: 1,
  },
  {
    arabic: "خبز",
    transliteration: "Khubz",
    english: "Bread",
    category: "food",
    difficulty: 1,
  },
  {
    arabic: "لحم",
    transliteration: "Lahm",
    english: "Meat",
    category: "food",
    difficulty: 1,
  },
  {
    arabic: "فاكهة",
    transliteration: "Fakihah",
    english: "Fruit",
    category: "food",
    difficulty: 1,
  },
  {
    arabic: "حليب",
    transliteration: "Halib",
    english: "Milk",
    category: "food",
    difficulty: 1,
  },
  {
    arabic: "أرز",
    transliteration: "Aruzz",
    english: "Rice",
    category: "food",
    difficulty: 1,
  },
  {
    arabic: "تمر",
    transliteration: "Tamr",
    english: "Dates",
    category: "food",
    difficulty: 1,
  },
  {
    arabic: "شاي",
    transliteration: "Shay",
    english: "Tea",
    category: "food",
    difficulty: 1,
  },
  {
    arabic: "قهوة",
    transliteration: "Qahwa",
    english: "Coffee",
    category: "food",
    difficulty: 1,
  },
  {
    arabic: "عسل",
    transliteration: "Asal",
    english: "Honey",
    category: "food",
    difficulty: 1,
  },
  {
    arabic: "سمك",
    transliteration: "Samak",
    english: "Fish",
    category: "food",
    difficulty: 1,
  },
  {
    arabic: "دجاج",
    transliteration: "Dajaj",
    english: "Chicken",
    category: "food",
    difficulty: 1,
  },
  {
    arabic: "خضار",
    transliteration: "Khudar",
    english: "Vegetables",
    category: "food",
    difficulty: 1,
  },
  {
    arabic: "زيت",
    transliteration: "Zayt",
    english: "Oil",
    category: "food",
    difficulty: 1,
  },
  {
    arabic: "ملح",
    transliteration: "Milh",
    english: "Salt",
    category: "food",
    difficulty: 1,
  },
  {
    arabic: "سكر",
    transliteration: "Sukkar",
    english: "Sugar",
    category: "food",
    difficulty: 1,
  },
  {
    arabic: "لبن",
    transliteration: "Laban",
    english: "Yogurt",
    category: "food",
    difficulty: 1,
  },
  {
    arabic: "بيض",
    transliteration: "Bayd",
    english: "Eggs",
    category: "food",
    difficulty: 1,
  },
  {
    arabic: "جبن",
    transliteration: "Jubn",
    english: "Cheese",
    category: "food",
    difficulty: 1,
  },
  {
    arabic: "طعام",
    transliteration: "Taam",
    english: "Food",
    category: "food",
    difficulty: 1,
  },
  {
    arabic: "تفاح",
    transliteration: "Tuffah",
    english: "Apple",
    category: "food",
    difficulty: 1,
  },
  {
    arabic: "برتقال",
    transliteration: "Burtuqal",
    english: "Orange",
    category: "food",
    difficulty: 2,
  },
  {
    arabic: "موز",
    transliteration: "Mawz",
    english: "Banana",
    category: "food",
    difficulty: 1,
  },
  {
    arabic: "عنب",
    transliteration: "Inab",
    english: "Grapes",
    category: "food",
    difficulty: 1,
  },
  {
    arabic: "زيتون",
    transliteration: "Zaytun",
    english: "Olives",
    category: "food",
    difficulty: 2,
  },
  {
    arabic: "حمص",
    transliteration: "Hummus",
    english: "Chickpeas/Hummus",
    category: "food",
    difficulty: 2,
  },
  {
    arabic: "زبدة",
    transliteration: "Zubdah",
    english: "Butter",
    category: "food",
    difficulty: 2,
  },
  {
    arabic: "فلفل",
    transliteration: "Fulful",
    english: "Pepper",
    category: "food",
    difficulty: 2,
  },

  // ============================================================================
  // NATURE (25 words)
  // ============================================================================
  {
    arabic: "شمس",
    transliteration: "Shams",
    english: "Sun",
    category: "nature",
    difficulty: 1,
  },
  {
    arabic: "قمر",
    transliteration: "Qamar",
    english: "Moon",
    category: "nature",
    difficulty: 1,
  },
  {
    arabic: "نجم",
    transliteration: "Najm",
    english: "Star",
    category: "nature",
    difficulty: 1,
  },
  {
    arabic: "سماء",
    transliteration: "Samaa",
    english: "Sky",
    category: "nature",
    difficulty: 1,
  },
  {
    arabic: "بحر",
    transliteration: "Bahr",
    english: "Sea",
    category: "nature",
    difficulty: 1,
  },
  {
    arabic: "جبل",
    transliteration: "Jabal",
    english: "Mountain",
    category: "nature",
    difficulty: 1,
  },
  {
    arabic: "شجرة",
    transliteration: "Shajarah",
    english: "Tree",
    category: "nature",
    difficulty: 1,
  },
  {
    arabic: "وردة",
    transliteration: "Wardah",
    english: "Flower",
    category: "nature",
    difficulty: 1,
  },
  {
    arabic: "نهر",
    transliteration: "Nahr",
    english: "River",
    category: "nature",
    difficulty: 1,
  },
  {
    arabic: "أرض",
    transliteration: "Ard",
    english: "Earth/Land",
    category: "nature",
    difficulty: 1,
  },
  {
    arabic: "ريح",
    transliteration: "Rih",
    english: "Wind",
    category: "nature",
    difficulty: 2,
  },
  {
    arabic: "مطر",
    transliteration: "Matar",
    english: "Rain",
    category: "nature",
    difficulty: 1,
  },
  {
    arabic: "سحاب",
    transliteration: "Sahab",
    english: "Cloud",
    category: "nature",
    difficulty: 2,
  },
  {
    arabic: "حديقة",
    transliteration: "Hadiqah",
    english: "Garden",
    category: "nature",
    difficulty: 2,
  },
  {
    arabic: "صحراء",
    transliteration: "Sahraa",
    english: "Desert",
    category: "nature",
    difficulty: 2,
  },
  {
    arabic: "غابة",
    transliteration: "Ghabah",
    english: "Forest",
    category: "nature",
    difficulty: 2,
  },
  {
    arabic: "ثلج",
    transliteration: "Thalj",
    english: "Snow",
    category: "nature",
    difficulty: 2,
  },
  {
    arabic: "نار",
    transliteration: "Nar",
    english: "Fire",
    category: "nature",
    difficulty: 1,
  },
  {
    arabic: "حجر",
    transliteration: "Hajar",
    english: "Stone",
    category: "nature",
    difficulty: 2,
  },
  {
    arabic: "رمل",
    transliteration: "Raml",
    english: "Sand",
    category: "nature",
    difficulty: 2,
  },
  {
    arabic: "بحيرة",
    transliteration: "Buhayrah",
    english: "Lake",
    category: "nature",
    difficulty: 2,
  },
  {
    arabic: "ورق",
    transliteration: "Waraq",
    english: "Leaf/Paper",
    category: "nature",
    difficulty: 2,
  },
  {
    arabic: "جذر",
    transliteration: "Jidhr",
    english: "Root",
    category: "nature",
    difficulty: 3,
  },
  {
    arabic: "بذرة",
    transliteration: "Bidhrah",
    english: "Seed",
    category: "nature",
    difficulty: 2,
  },
  {
    arabic: "عشب",
    transliteration: "Ushb",
    english: "Grass",
    category: "nature",
    difficulty: 2,
  },

  // ============================================================================
  // NUMBERS (20 words)
  // ============================================================================
  {
    arabic: "واحد",
    transliteration: "Wahid",
    english: "One",
    category: "numbers",
    difficulty: 1,
  },
  {
    arabic: "اثنان",
    transliteration: "Ithnan",
    english: "Two",
    category: "numbers",
    difficulty: 1,
  },
  {
    arabic: "ثلاثة",
    transliteration: "Thalatha",
    english: "Three",
    category: "numbers",
    difficulty: 1,
  },
  {
    arabic: "أربعة",
    transliteration: "Arbaa",
    english: "Four",
    category: "numbers",
    difficulty: 1,
  },
  {
    arabic: "خمسة",
    transliteration: "Khamsah",
    english: "Five",
    category: "numbers",
    difficulty: 1,
  },
  {
    arabic: "ستة",
    transliteration: "Sittah",
    english: "Six",
    category: "numbers",
    difficulty: 1,
  },
  {
    arabic: "سبعة",
    transliteration: "Sabah",
    english: "Seven",
    category: "numbers",
    difficulty: 1,
  },
  {
    arabic: "ثمانية",
    transliteration: "Thamaniyah",
    english: "Eight",
    category: "numbers",
    difficulty: 1,
  },
  {
    arabic: "تسعة",
    transliteration: "Tisah",
    english: "Nine",
    category: "numbers",
    difficulty: 1,
  },
  {
    arabic: "عشرة",
    transliteration: "Asharah",
    english: "Ten",
    category: "numbers",
    difficulty: 1,
  },
  {
    arabic: "عشرون",
    transliteration: "Ishrun",
    english: "Twenty",
    category: "numbers",
    difficulty: 2,
  },
  {
    arabic: "ثلاثون",
    transliteration: "Thalathun",
    english: "Thirty",
    category: "numbers",
    difficulty: 2,
  },
  {
    arabic: "مائة",
    transliteration: "Miah",
    english: "One hundred",
    category: "numbers",
    difficulty: 2,
  },
  {
    arabic: "ألف",
    transliteration: "Alf",
    english: "One thousand",
    category: "numbers",
    difficulty: 2,
  },
  {
    arabic: "صفر",
    transliteration: "Sifr",
    english: "Zero",
    category: "numbers",
    difficulty: 1,
  },
  {
    arabic: "أحد عشر",
    transliteration: "Ahad ashar",
    english: "Eleven",
    category: "numbers",
    difficulty: 2,
  },
  {
    arabic: "خمسة عشر",
    transliteration: "Khamsah ashar",
    english: "Fifteen",
    category: "numbers",
    difficulty: 2,
  },
  {
    arabic: "أربعون",
    transliteration: "Arbaun",
    english: "Forty",
    category: "numbers",
    difficulty: 2,
  },
  {
    arabic: "خمسون",
    transliteration: "Khamsun",
    english: "Fifty",
    category: "numbers",
    difficulty: 2,
  },
  {
    arabic: "مليون",
    transliteration: "Milyun",
    english: "Million",
    category: "numbers",
    difficulty: 3,
  },

  // ============================================================================
  // DAILY LIFE (28 words)
  // ============================================================================
  {
    arabic: "كتاب",
    transliteration: "Kitab",
    english: "Book",
    category: "daily_life",
    difficulty: 1,
  },
  {
    arabic: "قلم",
    transliteration: "Qalam",
    english: "Pen",
    category: "daily_life",
    difficulty: 1,
  },
  {
    arabic: "بيت",
    transliteration: "Bayt",
    english: "House",
    category: "daily_life",
    difficulty: 1,
  },
  {
    arabic: "باب",
    transliteration: "Bab",
    english: "Door",
    category: "daily_life",
    difficulty: 1,
  },
  {
    arabic: "شباك",
    transliteration: "Shubbak",
    english: "Window",
    category: "daily_life",
    difficulty: 1,
  },
  {
    arabic: "كرسي",
    transliteration: "Kursi",
    english: "Chair",
    category: "daily_life",
    difficulty: 1,
  },
  {
    arabic: "طاولة",
    transliteration: "Tawilah",
    english: "Table",
    category: "daily_life",
    difficulty: 1,
  },
  {
    arabic: "طريق",
    transliteration: "Tariq",
    english: "Road/Path",
    category: "daily_life",
    difficulty: 1,
  },
  {
    arabic: "سيارة",
    transliteration: "Sayarah",
    english: "Car",
    category: "daily_life",
    difficulty: 1,
  },
  {
    arabic: "مدرسة",
    transliteration: "Madrasah",
    english: "School",
    category: "daily_life",
    difficulty: 1,
  },
  {
    arabic: "سوق",
    transliteration: "Suq",
    english: "Market",
    category: "daily_life",
    difficulty: 1,
  },
  {
    arabic: "مكتبة",
    transliteration: "Maktabah",
    english: "Library",
    category: "daily_life",
    difficulty: 2,
  },
  {
    arabic: "مفتاح",
    transliteration: "Miftah",
    english: "Key",
    category: "daily_life",
    difficulty: 1,
  },
  {
    arabic: "ساعة",
    transliteration: "Saah",
    english: "Clock/Hour",
    category: "daily_life",
    difficulty: 1,
  },
  {
    arabic: "هاتف",
    transliteration: "Hatif",
    english: "Telephone",
    category: "daily_life",
    difficulty: 2,
  },
  {
    arabic: "كمبيوتر",
    transliteration: "Kambyutar",
    english: "Computer",
    category: "daily_life",
    difficulty: 2,
  },
  {
    arabic: "مستشفى",
    transliteration: "Mustashfa",
    english: "Hospital",
    category: "daily_life",
    difficulty: 2,
  },
  {
    arabic: "دكان",
    transliteration: "Dukkan",
    english: "Shop",
    category: "daily_life",
    difficulty: 1,
  },
  {
    arabic: "ملابس",
    transliteration: "Malabis",
    english: "Clothes",
    category: "daily_life",
    difficulty: 2,
  },
  {
    arabic: "نقود",
    transliteration: "Nuqud",
    english: "Money",
    category: "daily_life",
    difficulty: 2,
  },
  {
    arabic: "غرفة",
    transliteration: "Ghurfah",
    english: "Room",
    category: "daily_life",
    difficulty: 1,
  },
  {
    arabic: "سرير",
    transliteration: "Sareer",
    english: "Bed",
    category: "daily_life",
    difficulty: 1,
  },
  {
    arabic: "مرآة",
    transliteration: "Mirah",
    english: "Mirror",
    category: "daily_life",
    difficulty: 2,
  },
  {
    arabic: "صابون",
    transliteration: "Sabun",
    english: "Soap",
    category: "daily_life",
    difficulty: 2,
  },
  {
    arabic: "منشفة",
    transliteration: "Minshafah",
    english: "Towel",
    category: "daily_life",
    difficulty: 2,
  },
  {
    arabic: "صحن",
    transliteration: "Sahn",
    english: "Plate",
    category: "daily_life",
    difficulty: 1,
  },
  {
    arabic: "كوب",
    transliteration: "Kub",
    english: "Cup",
    category: "daily_life",
    difficulty: 1,
  },
  {
    arabic: "ملعقة",
    transliteration: "Milaqah",
    english: "Spoon",
    category: "daily_life",
    difficulty: 2,
  },

  // ============================================================================
  // ISLAMIC TERMS (35 words)
  // ============================================================================
  {
    arabic: "إسلام",
    transliteration: "Islam",
    english: "Islam",
    category: "islamic_terms",
    difficulty: 1,
  },
  {
    arabic: "إيمان",
    transliteration: "Iman",
    english: "Faith",
    category: "islamic_terms",
    difficulty: 1,
  },
  {
    arabic: "إحسان",
    transliteration: "Ihsan",
    english: "Excellence",
    category: "islamic_terms",
    difficulty: 2,
  },
  {
    arabic: "توبة",
    transliteration: "Tawbah",
    english: "Repentance",
    category: "islamic_terms",
    difficulty: 2,
  },
  {
    arabic: "تقوى",
    transliteration: "Taqwa",
    english: "God-consciousness",
    category: "islamic_terms",
    difficulty: 2,
  },
  {
    arabic: "صبر",
    transliteration: "Sabr",
    english: "Patience",
    category: "islamic_terms",
    difficulty: 1,
  },
  {
    arabic: "شكر",
    transliteration: "Shukr",
    english: "Gratitude",
    category: "islamic_terms",
    difficulty: 1,
  },
  {
    arabic: "ذكر",
    transliteration: "Dhikr",
    english: "Remembrance of God",
    category: "islamic_terms",
    difficulty: 2,
  },
  {
    arabic: "جنة",
    transliteration: "Jannah",
    english: "Paradise",
    category: "islamic_terms",
    difficulty: 1,
  },
  {
    arabic: "نار",
    transliteration: "Nar",
    english: "Hellfire",
    category: "islamic_terms",
    difficulty: 1,
  },
  {
    arabic: "حق",
    transliteration: "Haqq",
    english: "Truth",
    category: "islamic_terms",
    difficulty: 2,
  },
  {
    arabic: "أمانة",
    transliteration: "Amanah",
    english: "Trust/Trustworthiness",
    category: "islamic_terms",
    difficulty: 2,
  },
  {
    arabic: "رحمة",
    transliteration: "Rahmah",
    english: "Mercy",
    category: "islamic_terms",
    difficulty: 1,
  },
  {
    arabic: "علم",
    transliteration: "Ilm",
    english: "Knowledge",
    category: "islamic_terms",
    difficulty: 1,
  },
  {
    arabic: "حكمة",
    transliteration: "Hikmah",
    english: "Wisdom",
    category: "islamic_terms",
    difficulty: 2,
  },
  {
    arabic: "نور",
    transliteration: "Nur",
    english: "Light",
    category: "islamic_terms",
    difficulty: 1,
  },
  {
    arabic: "قلب",
    transliteration: "Qalb",
    english: "Heart",
    category: "islamic_terms",
    difficulty: 1,
  },
  {
    arabic: "نفس",
    transliteration: "Nafs",
    english: "Soul/Self",
    category: "islamic_terms",
    difficulty: 2,
  },
  {
    arabic: "روح",
    transliteration: "Ruh",
    english: "Spirit",
    category: "islamic_terms",
    difficulty: 2,
  },
  {
    arabic: "زكاة",
    transliteration: "Zakah",
    english: "Charity/Alms",
    category: "islamic_terms",
    difficulty: 2,
  },
  {
    arabic: "صوم",
    transliteration: "Sawm",
    english: "Fasting",
    category: "islamic_terms",
    difficulty: 2,
  },
  {
    arabic: "حج",
    transliteration: "Hajj",
    english: "Pilgrimage",
    category: "islamic_terms",
    difficulty: 2,
  },
  {
    arabic: "شهادة",
    transliteration: "Shahadah",
    english: "Testimony of faith",
    category: "islamic_terms",
    difficulty: 2,
  },
  {
    arabic: "حديث",
    transliteration: "Hadith",
    english: "Prophetic tradition",
    category: "islamic_terms",
    difficulty: 3,
  },
  {
    arabic: "سنة",
    transliteration: "Sunnah",
    english: "Prophetic practice",
    category: "islamic_terms",
    difficulty: 3,
  },
  {
    arabic: "فقه",
    transliteration: "Fiqh",
    english: "Islamic jurisprudence",
    category: "islamic_terms",
    difficulty: 4,
  },
  {
    arabic: "عقيدة",
    transliteration: "Aqidah",
    english: "Islamic creed",
    category: "islamic_terms",
    difficulty: 4,
  },
  {
    arabic: "أخلاق",
    transliteration: "Akhlaq",
    english: "Moral character",
    category: "islamic_terms",
    difficulty: 3,
  },
  {
    arabic: "جهاد",
    transliteration: "Jihad",
    english: "Struggle/Effort",
    category: "islamic_terms",
    difficulty: 3,
  },
  {
    arabic: "عمرة",
    transliteration: "Umrah",
    english: "Minor pilgrimage",
    category: "islamic_terms",
    difficulty: 3,
  },
  {
    arabic: "رمضان",
    transliteration: "Ramadan",
    english: "Month of fasting",
    category: "islamic_terms",
    difficulty: 2,
  },
  {
    arabic: "عيد",
    transliteration: "Eid",
    english: "Festival/Celebration",
    category: "islamic_terms",
    difficulty: 2,
  },
  {
    arabic: "سورة",
    transliteration: "Surah",
    english: "Chapter of Quran",
    category: "islamic_terms",
    difficulty: 2,
  },
  {
    arabic: "آية",
    transliteration: "Ayah",
    english: "Verse of Quran",
    category: "islamic_terms",
    difficulty: 2,
  },
  {
    arabic: "بركة",
    transliteration: "Barakah",
    english: "Blessing",
    category: "islamic_terms",
    difficulty: 2,
  },

  // ============================================================================
  // BODY (16 words)
  // ============================================================================
  {
    arabic: "رأس",
    transliteration: "Ras",
    english: "Head",
    category: "body",
    difficulty: 1,
  },
  {
    arabic: "يد",
    transliteration: "Yad",
    english: "Hand",
    category: "body",
    difficulty: 1,
  },
  {
    arabic: "عين",
    transliteration: "Ayn",
    english: "Eye",
    category: "body",
    difficulty: 1,
  },
  {
    arabic: "قلب",
    transliteration: "Qalb",
    english: "Heart",
    category: "body",
    difficulty: 1,
  },
  {
    arabic: "رجل",
    transliteration: "Rijl",
    english: "Foot/Leg",
    category: "body",
    difficulty: 1,
  },
  {
    arabic: "أذن",
    transliteration: "Udhn",
    english: "Ear",
    category: "body",
    difficulty: 1,
  },
  {
    arabic: "أنف",
    transliteration: "Anf",
    english: "Nose",
    category: "body",
    difficulty: 1,
  },
  {
    arabic: "فم",
    transliteration: "Fam",
    english: "Mouth",
    category: "body",
    difficulty: 1,
  },
  {
    arabic: "شعر",
    transliteration: "Shaar",
    english: "Hair",
    category: "body",
    difficulty: 1,
  },
  {
    arabic: "ظهر",
    transliteration: "Dhahr",
    english: "Back",
    category: "body",
    difficulty: 2,
  },
  {
    arabic: "بطن",
    transliteration: "Batn",
    english: "Stomach/Belly",
    category: "body",
    difficulty: 2,
  },
  {
    arabic: "إصبع",
    transliteration: "Isbaa",
    english: "Finger",
    category: "body",
    difficulty: 2,
  },
  {
    arabic: "ركبة",
    transliteration: "Rukbah",
    english: "Knee",
    category: "body",
    difficulty: 2,
  },
  {
    arabic: "كتف",
    transliteration: "Katif",
    english: "Shoulder",
    category: "body",
    difficulty: 2,
  },
  {
    arabic: "صدر",
    transliteration: "Sadr",
    english: "Chest",
    category: "body",
    difficulty: 2,
  },
  {
    arabic: "لسان",
    transliteration: "Lisan",
    english: "Tongue",
    category: "body",
    difficulty: 2,
  },

  // ============================================================================
  // CLOTHING (13 words)
  // ============================================================================
  {
    arabic: "ثوب",
    transliteration: "Thawb",
    english: "Thobe/Garment",
    category: "clothing",
    difficulty: 2,
  },
  {
    arabic: "حجاب",
    transliteration: "Hijab",
    english: "Hijab/Headscarf",
    category: "clothing",
    difficulty: 2,
  },
  {
    arabic: "عباءة",
    transliteration: "Abaya",
    english: "Abaya/Cloak",
    category: "clothing",
    difficulty: 2,
  },
  {
    arabic: "قميص",
    transliteration: "Qamis",
    english: "Shirt",
    category: "clothing",
    difficulty: 1,
  },
  {
    arabic: "حذاء",
    transliteration: "Hidha",
    english: "Shoes",
    category: "clothing",
    difficulty: 1,
  },
  {
    arabic: "خاتم",
    transliteration: "Khatim",
    english: "Ring",
    category: "clothing",
    difficulty: 2,
  },
  {
    arabic: "ساعة",
    transliteration: "Saah",
    english: "Watch",
    category: "clothing",
    difficulty: 1,
  },
  {
    arabic: "نظارة",
    transliteration: "Nadharah",
    english: "Glasses",
    category: "clothing",
    difficulty: 2,
  },
  {
    arabic: "حقيبة",
    transliteration: "Haqibah",
    english: "Bag",
    category: "clothing",
    difficulty: 2,
  },
  {
    arabic: "قبعة",
    transliteration: "Qubbah",
    english: "Hat/Cap",
    category: "clothing",
    difficulty: 2,
  },
  {
    arabic: "جوارب",
    transliteration: "Jawarib",
    english: "Socks",
    category: "clothing",
    difficulty: 2,
  },
  {
    arabic: "سروال",
    transliteration: "Sirwal",
    english: "Pants",
    category: "clothing",
    difficulty: 2,
  },
  {
    arabic: "فستان",
    transliteration: "Fustan",
    english: "Dress",
    category: "clothing",
    difficulty: 2,
  },

  // ============================================================================
  // ANIMALS (13 words)
  // ============================================================================
  {
    arabic: "قط",
    transliteration: "Qit",
    english: "Cat",
    category: "animals",
    difficulty: 1,
  },
  {
    arabic: "كلب",
    transliteration: "Kalb",
    english: "Dog",
    category: "animals",
    difficulty: 1,
  },
  {
    arabic: "حصان",
    transliteration: "Hisan",
    english: "Horse",
    category: "animals",
    difficulty: 1,
  },
  {
    arabic: "جمل",
    transliteration: "Jamal",
    english: "Camel",
    category: "animals",
    difficulty: 1,
  },
  {
    arabic: "طائر",
    transliteration: "Tair",
    english: "Bird",
    category: "animals",
    difficulty: 1,
  },
  {
    arabic: "سمك",
    transliteration: "Samak",
    english: "Fish",
    category: "animals",
    difficulty: 1,
  },
  {
    arabic: "أسد",
    transliteration: "Asad",
    english: "Lion",
    category: "animals",
    difficulty: 1,
  },
  {
    arabic: "فيل",
    transliteration: "Fil",
    english: "Elephant",
    category: "animals",
    difficulty: 1,
  },
  {
    arabic: "نحلة",
    transliteration: "Nahlah",
    english: "Bee",
    category: "animals",
    difficulty: 2,
  },
  {
    arabic: "فراشة",
    transliteration: "Farashah",
    english: "Butterfly",
    category: "animals",
    difficulty: 2,
  },
  {
    arabic: "حمامة",
    transliteration: "Hamamah",
    english: "Dove/Pigeon",
    category: "animals",
    difficulty: 2,
  },
  {
    arabic: "خروف",
    transliteration: "Kharuf",
    english: "Sheep",
    category: "animals",
    difficulty: 2,
  },
  {
    arabic: "بقرة",
    transliteration: "Baqarah",
    english: "Cow",
    category: "animals",
    difficulty: 2,
  },

  // ============================================================================
  // COLORS (11 words)
  // ============================================================================
  {
    arabic: "أحمر",
    transliteration: "Ahmar",
    english: "Red",
    category: "colors",
    difficulty: 1,
  },
  {
    arabic: "أزرق",
    transliteration: "Azraq",
    english: "Blue",
    category: "colors",
    difficulty: 1,
  },
  {
    arabic: "أخضر",
    transliteration: "Akhdar",
    english: "Green",
    category: "colors",
    difficulty: 1,
  },
  {
    arabic: "أصفر",
    transliteration: "Asfar",
    english: "Yellow",
    category: "colors",
    difficulty: 1,
  },
  {
    arabic: "أبيض",
    transliteration: "Abyad",
    english: "White",
    category: "colors",
    difficulty: 1,
  },
  {
    arabic: "أسود",
    transliteration: "Aswad",
    english: "Black",
    category: "colors",
    difficulty: 1,
  },
  {
    arabic: "بني",
    transliteration: "Bunni",
    english: "Brown",
    category: "colors",
    difficulty: 2,
  },
  {
    arabic: "بنفسجي",
    transliteration: "Banafsaji",
    english: "Purple",
    category: "colors",
    difficulty: 2,
  },
  {
    arabic: "برتقالي",
    transliteration: "Burtuqali",
    english: "Orange",
    category: "colors",
    difficulty: 2,
  },
  {
    arabic: "وردي",
    transliteration: "Wardi",
    english: "Pink",
    category: "colors",
    difficulty: 2,
  },
  {
    arabic: "رمادي",
    transliteration: "Ramadi",
    english: "Gray",
    category: "colors",
    difficulty: 2,
  },

  // ============================================================================
  // TIME (13 words)
  // ============================================================================
  {
    arabic: "يوم",
    transliteration: "Yawm",
    english: "Day",
    category: "time",
    difficulty: 1,
  },
  {
    arabic: "ليلة",
    transliteration: "Laylah",
    english: "Night",
    category: "time",
    difficulty: 1,
  },
  {
    arabic: "صباح",
    transliteration: "Sabah",
    english: "Morning",
    category: "time",
    difficulty: 1,
  },
  {
    arabic: "مساء",
    transliteration: "Masaa",
    english: "Evening",
    category: "time",
    difficulty: 1,
  },
  {
    arabic: "أسبوع",
    transliteration: "Usbu",
    english: "Week",
    category: "time",
    difficulty: 2,
  },
  {
    arabic: "شهر",
    transliteration: "Shahr",
    english: "Month",
    category: "time",
    difficulty: 1,
  },
  {
    arabic: "سنة",
    transliteration: "Sanah",
    english: "Year",
    category: "time",
    difficulty: 1,
  },
  {
    arabic: "ساعة",
    transliteration: "Saah",
    english: "Hour",
    category: "time",
    difficulty: 1,
  },
  {
    arabic: "دقيقة",
    transliteration: "Daqiqah",
    english: "Minute",
    category: "time",
    difficulty: 2,
  },
  {
    arabic: "أمس",
    transliteration: "Ams",
    english: "Yesterday",
    category: "time",
    difficulty: 2,
  },
  {
    arabic: "غدا",
    transliteration: "Ghadan",
    english: "Tomorrow",
    category: "time",
    difficulty: 2,
  },
  {
    arabic: "الآن",
    transliteration: "Al-an",
    english: "Now",
    category: "time",
    difficulty: 1,
  },
  {
    arabic: "وقت",
    transliteration: "Waqt",
    english: "Time",
    category: "time",
    difficulty: 1,
  },

  // ============================================================================
  // EMOTIONS (13 words)
  // ============================================================================
  {
    arabic: "سعيد",
    transliteration: "Saeed",
    english: "Happy",
    category: "emotions",
    difficulty: 1,
  },
  {
    arabic: "حزين",
    transliteration: "Hazin",
    english: "Sad",
    category: "emotions",
    difficulty: 1,
  },
  {
    arabic: "غاضب",
    transliteration: "Ghadib",
    english: "Angry",
    category: "emotions",
    difficulty: 2,
  },
  {
    arabic: "خائف",
    transliteration: "Khaif",
    english: "Afraid",
    category: "emotions",
    difficulty: 2,
  },
  {
    arabic: "متعب",
    transliteration: "Mutaab",
    english: "Tired",
    category: "emotions",
    difficulty: 2,
  },
  {
    arabic: "جائع",
    transliteration: "Jai",
    english: "Hungry",
    category: "emotions",
    difficulty: 2,
  },
  {
    arabic: "عطشان",
    transliteration: "Atshan",
    english: "Thirsty",
    category: "emotions",
    difficulty: 2,
  },
  {
    arabic: "مريض",
    transliteration: "Marid",
    english: "Sick",
    category: "emotions",
    difficulty: 2,
  },
  {
    arabic: "قوي",
    transliteration: "Qawi",
    english: "Strong",
    category: "emotions",
    difficulty: 2,
  },
  {
    arabic: "ضعيف",
    transliteration: "Daeef",
    english: "Weak",
    category: "emotions",
    difficulty: 2,
  },
  {
    arabic: "فرح",
    transliteration: "Farah",
    english: "Joy",
    category: "emotions",
    difficulty: 2,
  },
  {
    arabic: "حب",
    transliteration: "Hubb",
    english: "Love",
    category: "emotions",
    difficulty: 1,
  },
  {
    arabic: "خوف",
    transliteration: "Khawf",
    english: "Fear",
    category: "emotions",
    difficulty: 2,
  },

  // ============================================================================
  // PLACES (13 words)
  // ============================================================================
  {
    arabic: "مدينة",
    transliteration: "Madinah",
    english: "City",
    category: "places",
    difficulty: 1,
  },
  {
    arabic: "قرية",
    transliteration: "Qaryah",
    english: "Village",
    category: "places",
    difficulty: 2,
  },
  {
    arabic: "سوق",
    transliteration: "Suq",
    english: "Market",
    category: "places",
    difficulty: 1,
  },
  {
    arabic: "مستشفى",
    transliteration: "Mustashfa",
    english: "Hospital",
    category: "places",
    difficulty: 2,
  },
  {
    arabic: "مطار",
    transliteration: "Matar",
    english: "Airport",
    category: "places",
    difficulty: 2,
  },
  {
    arabic: "شارع",
    transliteration: "Sharia",
    english: "Street",
    category: "places",
    difficulty: 1,
  },
  {
    arabic: "حديقة",
    transliteration: "Hadiqah",
    english: "Garden/Park",
    category: "places",
    difficulty: 2,
  },
  {
    arabic: "ملعب",
    transliteration: "Malāb",
    english: "Playground/Stadium",
    category: "places",
    difficulty: 2,
  },
  {
    arabic: "مكتبة",
    transliteration: "Maktabah",
    english: "Library",
    category: "places",
    difficulty: 2,
  },
  {
    arabic: "جامعة",
    transliteration: "Jamiāh",
    english: "University",
    category: "places",
    difficulty: 2,
  },
  {
    arabic: "مطعم",
    transliteration: "Matām",
    english: "Restaurant",
    category: "places",
    difficulty: 2,
  },
  {
    arabic: "فندق",
    transliteration: "Funduq",
    english: "Hotel",
    category: "places",
    difficulty: 2,
  },
  {
    arabic: "بنك",
    transliteration: "Bank",
    english: "Bank",
    category: "places",
    difficulty: 2,
  },

  // ============================================================================
  // VERBS (21 words)
  // ============================================================================
  {
    arabic: "كتب",
    transliteration: "Kataba",
    english: "Wrote",
    category: "verbs",
    difficulty: 2,
  },
  {
    arabic: "قرأ",
    transliteration: "Qaraa",
    english: "Read",
    category: "verbs",
    difficulty: 2,
  },
  {
    arabic: "أكل",
    transliteration: "Akala",
    english: "Ate",
    category: "verbs",
    difficulty: 2,
  },
  {
    arabic: "شرب",
    transliteration: "Shariba",
    english: "Drank",
    category: "verbs",
    difficulty: 2,
  },
  {
    arabic: "نام",
    transliteration: "Nama",
    english: "Slept",
    category: "verbs",
    difficulty: 2,
  },
  {
    arabic: "مشى",
    transliteration: "Masha",
    english: "Walked",
    category: "verbs",
    difficulty: 2,
  },
  {
    arabic: "جلس",
    transliteration: "Jalasa",
    english: "Sat",
    category: "verbs",
    difficulty: 2,
  },
  {
    arabic: "وقف",
    transliteration: "Waqafa",
    english: "Stood",
    category: "verbs",
    difficulty: 2,
  },
  {
    arabic: "فتح",
    transliteration: "Fataha",
    english: "Opened",
    category: "verbs",
    difficulty: 2,
  },
  {
    arabic: "أغلق",
    transliteration: "Aghlaqa",
    english: "Closed",
    category: "verbs",
    difficulty: 2,
  },
  {
    arabic: "دخل",
    transliteration: "Dakhala",
    english: "Entered",
    category: "verbs",
    difficulty: 2,
  },
  {
    arabic: "خرج",
    transliteration: "Kharaja",
    english: "Exited",
    category: "verbs",
    difficulty: 2,
  },
  {
    arabic: "سمع",
    transliteration: "Samiaa",
    english: "Heard",
    category: "verbs",
    difficulty: 2,
  },
  {
    arabic: "نظر",
    transliteration: "Nadhara",
    english: "Looked",
    category: "verbs",
    difficulty: 2,
  },
  {
    arabic: "عرف",
    transliteration: "Aarafa",
    english: "Knew",
    category: "verbs",
    difficulty: 2,
  },
  {
    arabic: "أحب",
    transliteration: "Ahabba",
    english: "Loved",
    category: "verbs",
    difficulty: 2,
  },
  {
    arabic: "سأل",
    transliteration: "Saala",
    english: "Asked",
    category: "verbs",
    difficulty: 2,
  },
  {
    arabic: "أجاب",
    transliteration: "Ajaba",
    english: "Answered",
    category: "verbs",
    difficulty: 2,
  },
  {
    arabic: "ساعد",
    transliteration: "Saaada",
    english: "Helped",
    category: "verbs",
    difficulty: 2,
  },
  {
    arabic: "بدأ",
    transliteration: "Badaa",
    english: "Began",
    category: "verbs",
    difficulty: 2,
  },
  {
    arabic: "ذهب",
    transliteration: "Dhahaba",
    english: "Went",
    category: "verbs",
    difficulty: 2,
  },

  // ============================================================================
  // ARABIC ALPHABET (28 letters)
  // ============================================================================
  {
    arabic: "ا",
    transliteration: "Alif",
    english: "First letter of Arabic alphabet",
    category: "alphabet",
    difficulty: 1,
  },
  {
    arabic: "ب",
    transliteration: "Ba",
    english: "Second letter of Arabic alphabet",
    category: "alphabet",
    difficulty: 1,
  },
  {
    arabic: "ت",
    transliteration: "Ta",
    english: "Third letter of Arabic alphabet",
    category: "alphabet",
    difficulty: 1,
  },
  {
    arabic: "ث",
    transliteration: "Tha",
    english: "Fourth letter of Arabic alphabet",
    category: "alphabet",
    difficulty: 1,
  },
  {
    arabic: "ج",
    transliteration: "Jim",
    english: "Fifth letter of Arabic alphabet",
    category: "alphabet",
    difficulty: 1,
  },
  {
    arabic: "ح",
    transliteration: "Ha",
    english: "Sixth letter of Arabic alphabet",
    category: "alphabet",
    difficulty: 1,
  },
  {
    arabic: "خ",
    transliteration: "Kha",
    english: "Seventh letter of Arabic alphabet",
    category: "alphabet",
    difficulty: 1,
  },
  {
    arabic: "د",
    transliteration: "Dal",
    english: "Eighth letter of Arabic alphabet",
    category: "alphabet",
    difficulty: 1,
  },
  {
    arabic: "ذ",
    transliteration: "Dhal",
    english: "Ninth letter of Arabic alphabet",
    category: "alphabet",
    difficulty: 1,
  },
  {
    arabic: "ر",
    transliteration: "Ra",
    english: "Tenth letter of Arabic alphabet",
    category: "alphabet",
    difficulty: 1,
  },
  {
    arabic: "ز",
    transliteration: "Zay",
    english: "Eleventh letter of Arabic alphabet",
    category: "alphabet",
    difficulty: 1,
  },
  {
    arabic: "س",
    transliteration: "Sin",
    english: "Twelfth letter of Arabic alphabet",
    category: "alphabet",
    difficulty: 1,
  },
  {
    arabic: "ش",
    transliteration: "Shin",
    english: "Thirteenth letter of Arabic alphabet",
    category: "alphabet",
    difficulty: 1,
  },
  {
    arabic: "ص",
    transliteration: "Sad",
    english: "Fourteenth letter of Arabic alphabet",
    category: "alphabet",
    difficulty: 1,
  },
  {
    arabic: "ض",
    transliteration: "Dad",
    english: "Fifteenth letter of Arabic alphabet",
    category: "alphabet",
    difficulty: 1,
  },
  {
    arabic: "ط",
    transliteration: "Ta (emphatic)",
    english: "Sixteenth letter of Arabic alphabet",
    category: "alphabet",
    difficulty: 1,
  },
  {
    arabic: "ظ",
    transliteration: "Dha (emphatic)",
    english: "Seventeenth letter of Arabic alphabet",
    category: "alphabet",
    difficulty: 1,
  },
  {
    arabic: "ع",
    transliteration: "Ain",
    english: "Eighteenth letter of Arabic alphabet",
    category: "alphabet",
    difficulty: 2,
  },
  {
    arabic: "غ",
    transliteration: "Ghain",
    english: "Nineteenth letter of Arabic alphabet",
    category: "alphabet",
    difficulty: 2,
  },
  {
    arabic: "ف",
    transliteration: "Fa",
    english: "Twentieth letter of Arabic alphabet",
    category: "alphabet",
    difficulty: 1,
  },
  {
    arabic: "ق",
    transliteration: "Qaf",
    english: "Twenty-first letter of Arabic alphabet",
    category: "alphabet",
    difficulty: 2,
  },
  {
    arabic: "ك",
    transliteration: "Kaf",
    english: "Twenty-second letter of Arabic alphabet",
    category: "alphabet",
    difficulty: 1,
  },
  {
    arabic: "ل",
    transliteration: "Lam",
    english: "Twenty-third letter of Arabic alphabet",
    category: "alphabet",
    difficulty: 1,
  },
  {
    arabic: "م",
    transliteration: "Mim",
    english: "Twenty-fourth letter of Arabic alphabet",
    category: "alphabet",
    difficulty: 1,
  },
  {
    arabic: "ن",
    transliteration: "Nun",
    english: "Twenty-fifth letter of Arabic alphabet",
    category: "alphabet",
    difficulty: 1,
  },
  {
    arabic: "ه",
    transliteration: "Ha",
    english: "Twenty-sixth letter of Arabic alphabet",
    category: "alphabet",
    difficulty: 1,
  },
  {
    arabic: "و",
    transliteration: "Waw",
    english: "Twenty-seventh letter of Arabic alphabet",
    category: "alphabet",
    difficulty: 1,
  },
  {
    arabic: "ي",
    transliteration: "Ya",
    english: "Twenty-eighth letter of Arabic alphabet",
    category: "alphabet",
    difficulty: 1,
  },
];

async function seedVocabulary() {
  try {
    defaultLogger.info("Starting vocabulary seed...");

    // Insert all vocabulary words (on conflict do nothing for idempotency)
    await db.insert(vocabularyWords).values(VOCABULARY).onConflictDoNothing();

    // Count by category for verification
    const categoryCounts: Record<string, number> = {};
    VOCABULARY.forEach((word) => {
      categoryCounts[word.category] = (categoryCounts[word.category] || 0) + 1;
    });

    defaultLogger.info("Vocabulary seed complete", {
      totalWords: VOCABULARY.length,
      categoryCounts,
    });

    process.exit(0);
  } catch (error) {
    defaultLogger.error(
      "Error seeding vocabulary",
      error instanceof Error ? error : new Error(String(error)),
    );
    process.exit(1);
  }
}

// Run seed
seedVocabulary();
