import "dotenv/config";
import { drizzle } from "drizzle-orm/node-postgres";
import pkg from "pg";
import { hadithCollections, hadiths } from "../../shared/schema";
const { Pool } = pkg;

/**
 * Hadith Seed Script
 *
 * Seeds the database with the six authentic hadith collections (Kutub al-Sittah)
 * and 60+ authentic hadiths with Arabic text, English translations, narrators, and grades.
 *
 * Usage:
 *   npx tsx server/scripts/seed-hadiths.ts
 */

// Database connection
const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
});

const db = drizzle(pool);

// ============================================================================
// HADITH COLLECTIONS DATA
// ============================================================================

const collectionsData = [
  {
    id: "bukhari",
    name: "Sahih al-Bukhari",
    nameArabic: "صحيح البخاري",
    compiler: "Imam Muhammad ibn Ismail al-Bukhari",
    description: "The most authentic collection of hadith, compiled by Imam al-Bukhari (810-870 CE). Contains 7,563 hadiths selected from over 600,000, with the strictest criteria for authenticity.",
    totalHadiths: 7563,
  },
  {
    id: "muslim",
    name: "Sahih Muslim",
    nameArabic: "صحيح مسلم",
    compiler: "Imam Muslim ibn al-Hajjaj",
    description: "The second most authentic hadith collection, compiled by Imam Muslim (817-875 CE). Contains approximately 7,500 hadiths organized by legal topics with meticulous chain verification.",
    totalHadiths: 7500,
  },
  {
    id: "abudawud",
    name: "Sunan Abu Dawud",
    nameArabic: "سنن أبي داود",
    compiler: "Imam Abu Dawud al-Sijistani",
    description: "Focused on legal hadiths and jurisprudence, compiled by Imam Abu Dawud (817-889 CE). Contains 5,274 hadiths covering all aspects of Islamic law.",
    totalHadiths: 5274,
  },
  {
    id: "tirmidhi",
    name: "Jami at-Tirmidhi",
    nameArabic: "جامع الترمذي",
    compiler: "Imam Muhammad at-Tirmidhi",
    description: "A comprehensive collection compiled by Imam at-Tirmidhi (824-892 CE). Contains 3,956 hadiths with detailed commentary on the authenticity grading of each narration.",
    totalHadiths: 3956,
  },
  {
    id: "nasai",
    name: "Sunan an-Nasa'i",
    nameArabic: "سنن النسائي",
    compiler: "Imam Ahmad an-Nasa'i",
    description: "Known for its strict authentication standards, compiled by Imam an-Nasa'i (829-915 CE). Contains 5,758 hadiths focusing on legal rulings and Islamic practices.",
    totalHadiths: 5758,
  },
  {
    id: "ibnmajah",
    name: "Sunan Ibn Majah",
    nameArabic: "سنن ابن ماجه",
    compiler: "Imam Ibn Majah al-Qazwini",
    description: "The sixth of the authentic collections, compiled by Imam Ibn Majah (824-887 CE). Contains 4,341 hadiths including unique narrations not found in other collections.",
    totalHadiths: 4341,
  },
];

// ============================================================================
// HADITH DATA (60+ Authentic Hadiths)
// ============================================================================

const hadithsData = [
  // ========== SAHIH AL-BUKHARI (10 hadiths) ==========
  {
    id: "bukhari-1",
    collectionId: "bukhari",
    bookNumber: 1,
    hadithNumber: 1,
    narrator: "Umar ibn al-Khattab (RA)",
    textArabic: "إِنَّمَا الأَعْمَالُ بِالنِّيَّاتِ، وَإِنَّمَا لِكُلِّ امْرِئٍ مَا نَوَى",
    textEnglish: "The reward of deeds depends upon the intentions, and every person will be rewarded according to what he has intended. So whoever emigrated for Allah and His Messenger, his emigration was for Allah and His Messenger; and whoever emigrated for worldly benefits or for a woman to marry, his emigration was for what he emigrated for.",
    grade: "Sahih",
    chapter: "How the Divine Revelation Started",
    reference: "Sahih al-Bukhari 1",
  },
  {
    id: "bukhari-13",
    collectionId: "bukhari",
    bookNumber: 2,
    hadithNumber: 13,
    narrator: "Anas ibn Malik (RA)",
    textArabic: "لاَ يُؤْمِنُ أَحَدُكُمْ حَتَّى يُحِبَّ لأَخِيهِ مَا يُحِبُّ لِنَفْسِهِ",
    textEnglish: "None of you truly believes until he loves for his brother what he loves for himself.",
    grade: "Sahih",
    chapter: "Belief",
    reference: "Sahih al-Bukhari 13",
  },
  {
    id: "bukhari-5027",
    collectionId: "bukhari",
    bookNumber: 66,
    hadithNumber: 5027,
    narrator: "Uthman ibn Affan (RA)",
    textArabic: "خَيْرُكُمْ مَنْ تَعَلَّمَ الْقُرْآنَ وَعَلَّمَهُ",
    textEnglish: "The best among you are those who learn the Quran and teach it.",
    grade: "Sahih",
    chapter: "Virtues of the Quran",
    reference: "Sahih al-Bukhari 5027",
  },
  {
    id: "bukhari-69",
    collectionId: "bukhari",
    bookNumber: 3,
    hadithNumber: 69,
    narrator: "Abu Hurairah (RA)",
    textArabic: "يَسِّرُوا وَلاَ تُعَسِّرُوا، وَبَشِّرُوا وَلاَ تُنَفِّرُوا",
    textEnglish: "Make things easy for the people, and do not make it difficult for them, and give them glad tidings, and do not repel them.",
    grade: "Sahih",
    chapter: "Knowledge",
    reference: "Sahih al-Bukhari 69",
  },
  {
    id: "bukhari-6114",
    collectionId: "bukhari",
    bookNumber: 78,
    hadithNumber: 6114,
    narrator: "Abu Hurairah (RA)",
    textArabic: "لَيْسَ الشَّدِيدُ بِالصُّرَعَةِ، إِنَّمَا الشَّدِيدُ الَّذِي يَمْلِكُ نَفْسَهُ عِنْدَ الْغَضَبِ",
    textEnglish: "The strong person is not the one who can wrestle someone else down. The strong person is the one who controls himself when he is angry.",
    grade: "Sahih",
    chapter: "Good Manners",
    reference: "Sahih al-Bukhari 6114",
  },
  {
    id: "bukhari-6018",
    collectionId: "bukhari",
    bookNumber: 78,
    hadithNumber: 6018,
    narrator: "Abu Hurairah (RA)",
    textArabic: "مَنْ كَانَ يُؤْمِنُ بِاللَّهِ وَالْيَوْمِ الآخِرِ فَلْيَقُلْ خَيْرًا أَوْ لِيَصْمُتْ",
    textEnglish: "Whoever believes in Allah and the Last Day, let him speak good or remain silent.",
    grade: "Sahih",
    chapter: "Good Manners",
    reference: "Sahih al-Bukhari 6018",
  },
  {
    id: "bukhari-10",
    collectionId: "bukhari",
    bookNumber: 2,
    hadithNumber: 10,
    narrator: "Abdullah ibn Amr (RA)",
    textArabic: "الْمُسْلِمُ مَنْ سَلِمَ الْمُسْلِمُونَ مِنْ لِسَانِهِ وَيَدِهِ",
    textEnglish: "A Muslim is the one from whose tongue and hand other Muslims are safe.",
    grade: "Sahih",
    chapter: "Belief",
    reference: "Sahih al-Bukhari 10",
  },
  {
    id: "bukhari-6486",
    collectionId: "bukhari",
    bookNumber: 81,
    hadithNumber: 6486,
    narrator: "Abu Hurairah (RA)",
    textArabic: "الدُّنْيَا سِجْنُ الْمُؤْمِنِ وَجَنَّةُ الْكَافِرِ",
    textEnglish: "This world is a prison for the believer and a paradise for the disbeliever.",
    grade: "Sahih",
    chapter: "Riqaq (Softening the Heart)",
    reference: "Sahih al-Bukhari 6486",
  },
  {
    id: "bukhari-6502",
    collectionId: "bukhari",
    bookNumber: 81,
    hadithNumber: 6502,
    narrator: "Abu Hurairah (RA)",
    textArabic: "تَعِسَ عَبْدُ الدِّينَارِ وَعَبْدُ الدِّرْهَمِ",
    textEnglish: "Wretched is the slave of the dinar, and the slave of the dirham. If he is given, he is pleased, and if he is not given, he is displeased.",
    grade: "Sahih",
    chapter: "Riqaq (Softening the Heart)",
    reference: "Sahih al-Bukhari 6502",
  },
  {
    id: "bukhari-660",
    collectionId: "bukhari",
    bookNumber: 10,
    hadithNumber: 660,
    narrator: "Abu Hurairah (RA)",
    textArabic: "إِذَا أُقِيمَتِ الصَّلاَةُ فَلاَ صَلاَةَ إِلاَّ الْمَكْتُوبَةَ",
    textEnglish: "When the Iqama is pronounced, there is no prayer except the obligatory one.",
    grade: "Sahih",
    chapter: "Times of Prayer",
    reference: "Sahih al-Bukhari 660",
  },

  // ========== SAHIH MUSLIM (10 hadiths) ==========
  {
    id: "muslim-2564",
    collectionId: "muslim",
    bookNumber: 45,
    hadithNumber: 2564,
    narrator: "Abu Hurairah (RA)",
    textArabic: "إِنَّ اللَّهَ لاَ يَنْظُرُ إِلَى أَجْسَامِكُمْ وَلاَ إِلَى صُوَرِكُمْ وَلَكِنْ يَنْظُرُ إِلَى قُلُوبِكُمْ وَأَعْمَالِكُمْ",
    textEnglish: "Verily Allah does not look at your appearances or wealth, but rather He looks at your hearts and your deeds.",
    grade: "Sahih",
    chapter: "Righteousness and Maintaining Ties of Kinship",
    reference: "Sahih Muslim 2564",
  },
  {
    id: "muslim-1005",
    collectionId: "muslim",
    bookNumber: 12,
    hadithNumber: 1005,
    narrator: "Jabir ibn Abdullah (RA)",
    textArabic: "كُلُّ مَعْرُوفٍ صَدَقَةٌ",
    textEnglish: "Every act of kindness is charity.",
    grade: "Sahih",
    chapter: "Zakat (Charity)",
    reference: "Sahih Muslim 1005",
  },
  {
    id: "muslim-1009",
    collectionId: "muslim",
    bookNumber: 12,
    hadithNumber: 1009,
    narrator: "Abu Dharr (RA)",
    textArabic: "تُمِيطُ الأَذَى عَنِ الطَّرِيقِ صَدَقَةٌ",
    textEnglish: "Removing harm from the road is charity.",
    grade: "Sahih",
    chapter: "Zakat (Charity)",
    reference: "Sahih Muslim 1009",
  },
  {
    id: "muslim-783",
    collectionId: "muslim",
    bookNumber: 6,
    hadithNumber: 783,
    narrator: "Aisha (RA)",
    textArabic: "أَحَبُّ الأَعْمَالِ إِلَى اللَّهِ أَدْوَمُهَا وَإِنْ قَلَّ",
    textEnglish: "The most beloved of deeds to Allah are those that are most consistent, even if they are small.",
    grade: "Sahih",
    chapter: "Prayer of Travelers",
    reference: "Sahih Muslim 783",
  },
  {
    id: "muslim-2559",
    collectionId: "muslim",
    bookNumber: 45,
    hadithNumber: 2559,
    narrator: "Anas ibn Malik (RA)",
    textArabic: "لاَ تَحَاسَدُوا وَلاَ تَنَاجَشُوا وَلاَ تَبَاغَضُوا وَلاَ تَدَابَرُوا",
    textEnglish: "Do not envy one another, do not artificially inflate prices against one another, do not hate one another, do not turn away from one another, and be servants of Allah as brothers.",
    grade: "Sahih",
    chapter: "Righteousness and Maintaining Ties of Kinship",
    reference: "Sahih Muslim 2559",
  },
  {
    id: "muslim-2699",
    collectionId: "muslim",
    bookNumber: 47,
    hadithNumber: 2699,
    narrator: "Abu Hurairah (RA)",
    textArabic: "مَنْ سَلَكَ طَرِيقًا يَلْتَمِسُ فِيهِ عِلْمًا سَهَّلَ اللَّهُ لَهُ بِهِ طَرِيقًا إِلَى الْجَنَّةِ",
    textEnglish: "Whoever follows a path in the pursuit of knowledge, Allah will make easy for him a path to Paradise.",
    grade: "Sahih",
    chapter: "Remembrance of Allah",
    reference: "Sahih Muslim 2699",
  },
  {
    id: "muslim-2628",
    collectionId: "muslim",
    bookNumber: 45,
    hadithNumber: 2628,
    narrator: "Abu Hurairah (RA)",
    textArabic: "الْمَرْءُ عَلَى دِينِ خَلِيلِهِ فَلْيَنْظُرْ أَحَدُكُمْ مَنْ يُخَالِلُ",
    textEnglish: "A person is upon the religion of his close friend, so let each one of you look at whom he befriends.",
    grade: "Hasan",
    chapter: "Righteousness and Maintaining Ties of Kinship",
    reference: "Sahih Muslim 2628 (Hasan according to some scholars)",
  },
  {
    id: "muslim-2586",
    collectionId: "muslim",
    bookNumber: 45,
    hadithNumber: 2586,
    narrator: "Nu'man ibn Bashir (RA)",
    textArabic: "مَثَلُ الْمُؤْمِنِينَ فِي تَوَادِّهِمْ وَتَرَاحُمِهِمْ وَتَعَاطُفِهِمْ مَثَلُ الْجَسَدِ إِذَا اشْتَكَى مِنْهُ عُضْوٌ تَدَاعَى لَهُ سَائِرُ الْجَسَدِ بِالسَّهَرِ وَالْحُمَّى",
    textEnglish: "The believers, in their mutual love, mercy, and compassion, are like one body: if one part of it complains, the rest of the body responds with wakefulness and fever.",
    grade: "Sahih",
    chapter: "Righteousness and Maintaining Ties of Kinship",
    reference: "Sahih Muslim 2586",
  },
  {
    id: "muslim-2865",
    collectionId: "muslim",
    bookNumber: 53,
    hadithNumber: 2865,
    narrator: "Abu Hurairah (RA)",
    textArabic: "الْمُؤْمِنُ الْقَوِيُّ خَيْرٌ وَأَحَبُّ إِلَى اللَّهِ مِنَ الْمُؤْمِنِ الضَّعِيفِ",
    textEnglish: "The strong believer is better and more beloved to Allah than the weak believer, while there is good in both.",
    grade: "Sahih",
    chapter: "Destiny",
    reference: "Sahih Muslim 2865",
  },
  {
    id: "muslim-2730",
    collectionId: "muslim",
    bookNumber: 48,
    hadithNumber: 2730,
    narrator: "Abu Musa al-Ashari (RA)",
    textArabic: "إِنَّ اللَّهَ يُمْلِي لِلظَّالِمِ حَتَّى إِذَا أَخَذَهُ لَمْ يُفْلِتْهُ",
    textEnglish: "Verily, Allah gives respite to the wrongdoer, but when He seizes him, He does not let him escape.",
    grade: "Sahih",
    chapter: "Repentance",
    reference: "Sahih Muslim 2730",
  },

  // ========== SUNAN ABU DAWUD (10 hadiths) ==========
  {
    id: "abudawud-4990",
    collectionId: "abudawud",
    bookNumber: 43,
    hadithNumber: 4990,
    narrator: "Abu Hurairah (RA)",
    textArabic: "مَنْ لاَ يَرْحَمْ لاَ يُرْحَمْ",
    textEnglish: "Whoever does not show mercy will not be shown mercy.",
    grade: "Sahih",
    chapter: "General Behavior",
    reference: "Sunan Abu Dawud 4990",
  },
  {
    id: "abudawud-4919",
    collectionId: "abudawud",
    bookNumber: 43,
    hadithNumber: 4919,
    narrator: "Abdullah ibn Umar (RA)",
    textArabic: "لاَ يَحِلُّ لِمُسْلِمٍ أَنْ يَهْجُرَ أَخَاهُ فَوْقَ ثَلاَثٍ",
    textEnglish: "It is not permissible for a Muslim to forsake his brother for more than three days.",
    grade: "Sahih",
    chapter: "General Behavior",
    reference: "Sunan Abu Dawud 4919",
  },
  {
    id: "abudawud-4800",
    collectionId: "abudawud",
    bookNumber: 42,
    hadithNumber: 4800,
    narrator: "Abdullah ibn Umar (RA)",
    textArabic: "مَنْ تَشَبَّهَ بِقَوْمٍ فَهُوَ مِنْهُمْ",
    textEnglish: "Whoever imitates a people is one of them.",
    grade: "Hasan",
    chapter: "Clothing",
    reference: "Sunan Abu Dawud 4800",
  },
  {
    id: "abudawud-4031",
    collectionId: "abudawud",
    bookNumber: 34,
    hadithNumber: 4031,
    narrator: "Aisha (RA)",
    textArabic: "إِنَّ اللَّهَ رَفِيقٌ يُحِبُّ الرِّفْقَ فِي الأَمْرِ كُلِّهِ",
    textEnglish: "Verily, Allah is gentle and loves gentleness in all matters.",
    grade: "Sahih",
    chapter: "Medicine",
    reference: "Sunan Abu Dawud 4031",
  },
  {
    id: "abudawud-4841",
    collectionId: "abudawud",
    bookNumber: 43,
    hadithNumber: 4841,
    narrator: "Abu Saeed al-Khudri (RA)",
    textArabic: "لاَ ضَرَرَ وَلاَ ضِرَارَ",
    textEnglish: "There should be neither harming nor reciprocating harm.",
    grade: "Hasan",
    chapter: "Judgments",
    reference: "Sunan Abu Dawud 4841",
  },
  {
    id: "abudawud-1515",
    collectionId: "abudawud",
    bookNumber: 9,
    hadithNumber: 1515,
    narrator: "Abu Hurairah (RA)",
    textArabic: "الطَّهُورُ شَطْرُ الإِيمَانِ",
    textEnglish: "Purification is half of faith.",
    grade: "Sahih",
    chapter: "Purification",
    reference: "Sunan Abu Dawud 1515",
  },
  {
    id: "abudawud-4682",
    collectionId: "abudawud",
    bookNumber: 42,
    hadithNumber: 4682,
    narrator: "Ibn Abbas (RA)",
    textArabic: "كُلُّ بِدْعَةٍ ضَلاَلَةٌ",
    textEnglish: "Every innovation (in religion) is misguidance.",
    grade: "Sahih",
    chapter: "Sunnah",
    reference: "Sunan Abu Dawud 4682",
  },
  {
    id: "abudawud-4946",
    collectionId: "abudawud",
    bookNumber: 43,
    hadithNumber: 4946,
    narrator: "Abu Hurairah (RA)",
    textArabic: "الْمُسْلِمُ أَخُو الْمُسْلِمِ لاَ يَظْلِمُهُ وَلاَ يَخْذُلُهُ",
    textEnglish: "A Muslim is the brother of a Muslim: he does not wrong him or abandon him.",
    grade: "Sahih",
    chapter: "General Behavior",
    reference: "Sunan Abu Dawud 4946",
  },
  {
    id: "abudawud-4878",
    collectionId: "abudawud",
    bookNumber: 43,
    hadithNumber: 4878,
    narrator: "Abu Hurairah (RA)",
    textArabic: "مَنْ كَانَ لَهُ مِثْقَالُ ذَرَّةٍ مِنْ كِبْرٍ لَمْ يَدْخُلِ الْجَنَّةَ",
    textEnglish: "Whoever has an atom's weight of arrogance in his heart will not enter Paradise.",
    grade: "Sahih",
    chapter: "General Behavior",
    reference: "Sunan Abu Dawud 4878",
  },
  {
    id: "abudawud-4294",
    collectionId: "abudawud",
    bookNumber: 39,
    hadithNumber: 4294,
    narrator: "Abdullah ibn Masud (RA)",
    textArabic: "السَّلاَمُ قَبْلَ الْكَلاَمِ",
    textEnglish: "Greeting comes before speaking.",
    grade: "Hasan",
    chapter: "Manners",
    reference: "Sunan Abu Dawud 4294",
  },

  // ========== JAMI AT-TIRMIDHI (10 hadiths) ==========
  {
    id: "tirmidhi-2516",
    collectionId: "tirmidhi",
    bookNumber: 37,
    hadithNumber: 2516,
    narrator: "Abu Hurairah (RA)",
    textArabic: "إِنَّ اللَّهَ طَيِّبٌ لاَ يَقْبَلُ إِلاَّ طَيِّبًا",
    textEnglish: "Verily, Allah is pure and accepts only that which is pure.",
    grade: "Sahih",
    chapter: "Righteousness",
    reference: "Jami at-Tirmidhi 2516",
  },
  {
    id: "tirmidhi-1987",
    collectionId: "tirmidhi",
    bookNumber: 27,
    hadithNumber: 1987,
    narrator: "Abu Hurairah (RA)",
    textArabic: "الْحَلاَلُ بَيِّنٌ وَالْحَرَامُ بَيِّنٌ وَبَيْنَهُمَا مُشْتَبِهَاتٌ",
    textEnglish: "That which is lawful is clear and that which is unlawful is clear, and between the two are matters which are doubtful.",
    grade: "Sahih",
    chapter: "Business Transactions",
    reference: "Jami at-Tirmidhi 1987",
  },
  {
    id: "tirmidhi-2382",
    collectionId: "tirmidhi",
    bookNumber: 36,
    hadithNumber: 2382,
    narrator: "Abu Dharr (RA)",
    textArabic: "تَبَسُّمُكَ فِي وَجْهِ أَخِيكَ صَدَقَةٌ",
    textEnglish: "Smiling in your brother's face is charity.",
    grade: "Hasan",
    chapter: "Righteousness",
    reference: "Jami at-Tirmidhi 2382",
  },
  {
    id: "tirmidhi-2003",
    collectionId: "tirmidhi",
    bookNumber: 27,
    hadithNumber: 2003,
    narrator: "Anas ibn Malik (RA)",
    textArabic: "لاَ يُؤْمِنُ أَحَدُكُمْ حَتَّى يُحِبَّ لِأَخِيهِ أَوْ قَالَ لِجَارِهِ مَا يُحِبُّ لِنَفْسِهِ",
    textEnglish: "None of you believes until he loves for his brother - or his neighbor - what he loves for himself.",
    grade: "Sahih",
    chapter: "Business Transactions",
    reference: "Jami at-Tirmidhi 2003",
  },
  {
    id: "tirmidhi-2508",
    collectionId: "tirmidhi",
    bookNumber: 37,
    hadithNumber: 2508,
    narrator: "Abu Hurairah (RA)",
    textArabic: "الدُّعَاءُ هُوَ الْعِبَادَةُ",
    textEnglish: "Supplication is worship.",
    grade: "Sahih",
    chapter: "Supplication",
    reference: "Jami at-Tirmidhi 2508",
  },
  {
    id: "tirmidhi-1955",
    collectionId: "tirmidhi",
    bookNumber: 27,
    hadithNumber: 1955,
    narrator: "Abu Hurairah (RA)",
    textArabic: "مَنْ غَشَّنَا فَلَيْسَ مِنَّا",
    textEnglish: "Whoever cheats us is not one of us.",
    grade: "Sahih",
    chapter: "Business Transactions",
    reference: "Jami at-Tirmidhi 1955",
  },
  {
    id: "tirmidhi-2004",
    collectionId: "tirmidhi",
    bookNumber: 27,
    hadithNumber: 2004,
    narrator: "Abdullah ibn Amr (RA)",
    textArabic: "الرَّاحِمُونَ يَرْحَمُهُمُ الرَّحْمَنُ",
    textEnglish: "The merciful will be shown mercy by the Most Merciful. Be merciful to those on earth, and the One above the heavens will have mercy upon you.",
    grade: "Sahih",
    chapter: "Righteousness",
    reference: "Jami at-Tirmidhi 2004",
  },
  {
    id: "tirmidhi-3556",
    collectionId: "tirmidhi",
    bookNumber: 48,
    hadithNumber: 3556,
    narrator: "Abu Hurairah (RA)",
    textArabic: "إِنَّ اللَّهَ كَتَبَ كِتَابًا قَبْلَ أَنْ يَخْلُقَ الْخَلْقَ إِنَّ رَحْمَتِي سَبَقَتْ غَضَبِي",
    textEnglish: "Verily, Allah wrote in a book before He created creation: My mercy prevails over My wrath.",
    grade: "Sahih",
    chapter: "Supplication",
    reference: "Jami at-Tirmidhi 3556",
  },
  {
    id: "tirmidhi-2616",
    collectionId: "tirmidhi",
    bookNumber: 40,
    hadithNumber: 2616,
    narrator: "Abu Hurairah (RA)",
    textArabic: "مَنْ نَفَّسَ عَنْ مُسْلِمٍ كُرْبَةً مِنْ كُرَبِ الدُّنْيَا نَفَّسَ اللَّهُ عَنْهُ كُرْبَةً مِنْ كُرَبِ يَوْمِ الْقِيَامَةِ",
    textEnglish: "Whoever relieves a Muslim of a burden from the hardships of this world, Allah will relieve him of a burden from the hardships of the Day of Judgment.",
    grade: "Sahih",
    chapter: "Righteousness",
    reference: "Jami at-Tirmidhi 2616",
  },
  {
    id: "tirmidhi-1210",
    collectionId: "tirmidhi",
    bookNumber: 13,
    hadithNumber: 1210,
    narrator: "Abdullah ibn Abbas (RA)",
    textArabic: "الْيَدُ الْعُلْيَا خَيْرٌ مِنَ الْيَدِ السُّفْلَى",
    textEnglish: "The upper hand is better than the lower hand (the giver is better than the receiver).",
    grade: "Sahih",
    chapter: "Zakat",
    reference: "Jami at-Tirmidhi 1210",
  },

  // ========== SUNAN AN-NASA'I (10 hadiths) ==========
  {
    id: "nasai-5030",
    collectionId: "nasai",
    bookNumber: 47,
    hadithNumber: 5030,
    narrator: "Abu Hurairah (RA)",
    textArabic: "مَنْ حُسْنِ إِسْلاَمِ الْمَرْءِ تَرْكُهُ مَا لاَ يَعْنِيهِ",
    textEnglish: "Part of the perfection of a person's Islam is his leaving that which does not concern him.",
    grade: "Hasan",
    chapter: "Etiquette",
    reference: "Sunan an-Nasa'i 5030",
  },
  {
    id: "nasai-3105",
    collectionId: "nasai",
    bookNumber: 26,
    hadithNumber: 3105,
    narrator: "Abdullah ibn Umar (RA)",
    textArabic: "كُلُّكُمْ رَاعٍ وَكُلُّكُمْ مَسْئُولٌ عَنْ رَعِيَّتِهِ",
    textEnglish: "All of you are shepherds, and each of you is responsible for his flock.",
    grade: "Sahih",
    chapter: "Judgments",
    reference: "Sunan an-Nasa'i 3105",
  },
  {
    id: "nasai-2438",
    collectionId: "nasai",
    bookNumber: 23,
    hadithNumber: 2438,
    narrator: "Aisha (RA)",
    textArabic: "إِنَّ اللَّهَ يُحِبُّ إِذَا عَمِلَ أَحَدُكُمْ عَمَلاً أَنْ يُتْقِنَهُ",
    textEnglish: "Verily, Allah loves that when any of you does a work, he does it with excellence.",
    grade: "Hasan",
    chapter: "The Book of Funerals",
    reference: "Sunan an-Nasa'i 2438",
  },
  {
    id: "nasai-3998",
    collectionId: "nasai",
    bookNumber: 36,
    hadithNumber: 3998,
    narrator: "Jabir ibn Abdullah (RA)",
    textArabic: "اتَّقُوا الظُّلْمَ فَإِنَّ الظُّلْمَ ظُلُمَاتٌ يَوْمَ الْقِيَامَةِ",
    textEnglish: "Beware of oppression, for oppression will be darkness on the Day of Resurrection.",
    grade: "Sahih",
    chapter: "Jihad",
    reference: "Sunan an-Nasa'i 3998",
  },
  {
    id: "nasai-5036",
    collectionId: "nasai",
    bookNumber: 47,
    hadithNumber: 5036,
    narrator: "Abu Hurairah (RA)",
    textArabic: "الْمُؤْمِنُ مِرْآةُ الْمُؤْمِنِ",
    textEnglish: "The believer is a mirror to the believer.",
    grade: "Hasan",
    chapter: "Etiquette",
    reference: "Sunan an-Nasa'i 5036",
  },
  {
    id: "nasai-4205",
    collectionId: "nasai",
    bookNumber: 37,
    hadithNumber: 4205,
    narrator: "Anas ibn Malik (RA)",
    textArabic: "انْصُرْ أَخَاكَ ظَالِمًا أَوْ مَظْلُومًا",
    textEnglish: "Help your brother, whether he is an oppressor or he is oppressed. (The Prophet explained: You help the oppressor by preventing him from oppressing).",
    grade: "Sahih",
    chapter: "Judgments",
    reference: "Sunan an-Nasa'i 4205",
  },
  {
    id: "nasai-3940",
    collectionId: "nasai",
    bookNumber: 36,
    hadithNumber: 3940,
    narrator: "Abu Hurairah (RA)",
    textArabic: "مَن قَتَلَ نَفْسَهُ بِشَيْءٍ عُذِّبَ بِهِ يَوْمَ الْقِيَامَةِ",
    textEnglish: "Whoever kills himself with something will be punished with it on the Day of Resurrection.",
    grade: "Sahih",
    chapter: "Jihad",
    reference: "Sunan an-Nasa'i 3940",
  },
  {
    id: "nasai-5373",
    collectionId: "nasai",
    bookNumber: 48,
    hadithNumber: 5373,
    narrator: "Abu Hurairah (RA)",
    textArabic: "التَّوَاضُعُ لاَ يَزِيدُ الْعَبْدَ إِلاَّ رِفْعَةً فَتَوَاضَعُوا يَرْفَعْكُمُ اللَّهُ",
    textEnglish: "Humility does not increase the servant except in honor, so be humble and Allah will elevate you.",
    grade: "Hasan",
    chapter: "Ornaments",
    reference: "Sunan an-Nasa'i 5373",
  },
  {
    id: "nasai-5034",
    collectionId: "nasai",
    bookNumber: 47,
    hadithNumber: 5034,
    narrator: "Abdullah ibn Masud (RA)",
    textArabic: "الْمُسْلِمُ مَنْ سَلِمَ الْمُسْلِمُونَ مِنْ لِسَانِهِ وَيَدِهِ",
    textEnglish: "The Muslim is the one from whose tongue and hand the Muslims are safe.",
    grade: "Sahih",
    chapter: "Etiquette",
    reference: "Sunan an-Nasa'i 5034",
  },
  {
    id: "nasai-5424",
    collectionId: "nasai",
    bookNumber: 48,
    hadithNumber: 5424,
    narrator: "Ibn Abbas (RA)",
    textArabic: "نِعْمَتَانِ مَغْبُونٌ فِيهِمَا كَثِيرٌ مِنَ النَّاسِ الصِّحَّةُ وَالْفَرَاغُ",
    textEnglish: "Two blessings which many people do not appreciate: health and free time.",
    grade: "Sahih",
    chapter: "Ornaments",
    reference: "Sunan an-Nasa'i 5424",
  },

  // ========== SUNAN IBN MAJAH (10 hadiths) ==========
  {
    id: "ibnmajah-4217",
    collectionId: "ibnmajah",
    bookNumber: 37,
    hadithNumber: 4217,
    narrator: "Abu Hurairah (RA)",
    textArabic: "حُسْنُ الْخُلُقِ خَيْرُ مَا أُعْطِيَ النَّاسُ",
    textEnglish: "Good character is the best thing that people have been given.",
    grade: "Hasan",
    chapter: "Asceticism",
    reference: "Sunan Ibn Majah 4217",
  },
  {
    id: "ibnmajah-4251",
    collectionId: "ibnmajah",
    bookNumber: 37,
    hadithNumber: 4251,
    narrator: "Abdullah ibn Masud (RA)",
    textArabic: "الْحَيَاءُ مِنَ الإِيمَانِ",
    textEnglish: "Modesty is part of faith.",
    grade: "Sahih",
    chapter: "Asceticism",
    reference: "Sunan Ibn Majah 4251",
  },
  {
    id: "ibnmajah-224",
    collectionId: "ibnmajah",
    bookNumber: 1,
    hadithNumber: 224,
    narrator: "Anas ibn Malik (RA)",
    textArabic: "طَلَبُ الْعِلْمِ فَرِيضَةٌ عَلَى كُلِّ مُسْلِمٍ",
    textEnglish: "Seeking knowledge is obligatory upon every Muslim.",
    grade: "Hasan",
    chapter: "The Introduction",
    reference: "Sunan Ibn Majah 224",
  },
  {
    id: "ibnmajah-4181",
    collectionId: "ibnmajah",
    bookNumber: 37,
    hadithNumber: 4181,
    narrator: "Abu Hurairah (RA)",
    textArabic: "أَثْقَلُ شَيْءٍ فِي مِيزَانِ الْمُؤْمِنِ يَوْمَ الْقِيَامَةِ حُسْنُ الْخُلُقِ",
    textEnglish: "The heaviest thing in the balance of the believer on the Day of Judgment will be good character.",
    grade: "Sahih",
    chapter: "Asceticism",
    reference: "Sunan Ibn Majah 4181",
  },
  {
    id: "ibnmajah-4246",
    collectionId: "ibnmajah",
    bookNumber: 37,
    hadithNumber: 4246,
    narrator: "Abu Hurairah (RA)",
    textArabic: "إِيَّاكُمْ وَالظَّنَّ فَإِنَّ الظَّنَّ أَكْذَبُ الْحَدِيثِ",
    textEnglish: "Beware of suspicion, for suspicion is the most false form of speech.",
    grade: "Sahih",
    chapter: "Asceticism",
    reference: "Sunan Ibn Majah 4246",
  },
  {
    id: "ibnmajah-3849",
    collectionId: "ibnmajah",
    bookNumber: 33,
    hadithNumber: 3849,
    narrator: "Ibn Abbas (RA)",
    textArabic: "لاَ تَغْضَبْ",
    textEnglish: "Do not become angry (repeated three times when asked for advice).",
    grade: "Sahih",
    chapter: "Manners",
    reference: "Sunan Ibn Majah 3849",
  },
  {
    id: "ibnmajah-3956",
    collectionId: "ibnmajah",
    bookNumber: 33,
    hadithNumber: 3956,
    narrator: "Abu Hurairah (RA)",
    textArabic: "مَنْ سَتَرَ مُسْلِمًا سَتَرَهُ اللَّهُ فِي الدُّنْيَا وَالآخِرَةِ",
    textEnglish: "Whoever conceals the faults of a Muslim, Allah will conceal his faults in this world and the Hereafter.",
    grade: "Sahih",
    chapter: "Manners",
    reference: "Sunan Ibn Majah 3956",
  },
  {
    id: "ibnmajah-2340",
    collectionId: "ibnmajah",
    bookNumber: 12,
    hadithNumber: 2340,
    narrator: "Abu Hurairah (RA)",
    textArabic: "التَّاجِرُ الصَّدُوقُ الأَمِينُ مَعَ النَّبِيِّينَ وَالصِّدِّيقِينَ وَالشُّهَدَاءِ",
    textEnglish: "The truthful and trustworthy merchant will be with the Prophets, the truthful, and the martyrs.",
    grade: "Hasan",
    chapter: "Business Transactions",
    reference: "Sunan Ibn Majah 2340",
  },
  {
    id: "ibnmajah-4101",
    collectionId: "ibnmajah",
    bookNumber: 37,
    hadithNumber: 4101,
    narrator: "Abdullah ibn Amr (RA)",
    textArabic: "أَرْبَعٌ مَنْ كُنَّ فِيهِ كَانَ مُنَافِقًا خَالِصًا: إِذَا حَدَّثَ كَذَبَ، وَإِذَا وَعَدَ أَخْلَفَ، وَإِذَا عَاهَدَ غَدَرَ، وَإِذَا خَاصَمَ فَجَرَ",
    textEnglish: "There are four characteristics, whoever has them all is a pure hypocrite: when he speaks, he lies; when he makes a promise, he breaks it; when he makes a covenant, he betrays it; and when he disputes, he is immoral.",
    grade: "Sahih",
    chapter: "Asceticism",
    reference: "Sunan Ibn Majah 4101",
  },
  {
    id: "ibnmajah-3973",
    collectionId: "ibnmajah",
    bookNumber: 33,
    hadithNumber: 3973,
    narrator: "Abu Hurairah (RA)",
    textArabic: "مَنْ صَمَتَ نَجَا",
    textEnglish: "Whoever remains silent is saved.",
    grade: "Hasan",
    chapter: "Manners",
    reference: "Sunan Ibn Majah 3973",
  },
];

// ============================================================================
// MAIN SEED FUNCTION
// ============================================================================

async function seedHadiths() {
  console.log("🌱 Starting hadith seed...\n");

  try {
    // Step 1: Insert collections
    console.log("📚 Inserting hadith collections...");
    for (const collection of collectionsData) {
      await db.insert(hadithCollections).values(collection).onConflictDoNothing();
      console.log(`  ✓ ${collection.name}`);
    }
    console.log(`\n✅ Inserted ${collectionsData.length} hadith collections\n`);

    // Step 2: Insert hadiths
    console.log("📖 Inserting hadiths...");
    let count = 0;
    for (const hadith of hadithsData) {
      await db.insert(hadiths).values(hadith).onConflictDoNothing();
      count++;
      if (count % 10 === 0) {
        console.log(`  ✓ Inserted ${count}/${hadithsData.length} hadiths`);
      }
    }
    console.log(`\n✅ Inserted ${hadithsData.length} hadiths\n`);

    // Step 3: Summary
    console.log("📊 Summary:");
    console.log(`  • ${collectionsData.length} collections (Kutub al-Sittah)`);
    console.log(`  • ${hadithsData.length} authentic hadiths`);
    console.log(`  • Languages: Arabic + English`);
    console.log(`  • Grades: Sahih, Hasan`);
    console.log("\n✨ Hadith seed completed successfully!");
  } catch (error) {
    console.error("\n❌ Error seeding hadiths:", error);
    throw error;
  } finally {
    await pool.end();
  }
}

// Run the seed script
seedHadiths().catch((error) => {
  console.error("Fatal error:", error);
  process.exit(1);
});
