import "dotenv/config";
import { drizzle } from "drizzle-orm/node-postgres";
import pkg from "pg";
import { hadithCollections, hadiths } from "../../shared/schema";
const { Pool } = pkg;

// Database connection
const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
});

const db = drizzle(pool);

// ============================================================================
// HADITH COLLECTIONS DATA (Kutub al-Sittah - The Six Books)
// ============================================================================

const collectionsData = [
  {
    id: "bukhari",
    name: "Sahih al-Bukhari",
    nameArabic: "صحيح البخاري",
    compiler: "Imam Muhammad ibn Ismail al-Bukhari",
    description: "The most authentic collection of hadith, compiled by Imam al-Bukhari (810-870 CE). Contains 7,563 hadiths selected from over 600,000, with the strictest criteria for authenticity.",
    totalHadiths: 7563,
  },
  {
    id: "muslim",
    name: "Sahih Muslim",
    nameArabic: "صحيح مسلم",
    compiler: "Imam Muslim ibn al-Hajjaj",
    description: "The second most authentic hadith collection, compiled by Imam Muslim (817-875 CE). Contains approximately 7,500 hadiths organized by legal topics with meticulous chain verification.",
    totalHadiths: 7500,
  },
  {
    id: "abudawud",
    name: "Sunan Abu Dawud",
    nameArabic: "سنن أبي داود",
    compiler: "Imam Abu Dawud al-Sijistani",
    description: "Focused on legal hadiths and jurisprudence, compiled by Imam Abu Dawud (817-889 CE). Contains 5,274 hadiths covering all aspects of Islamic law.",
    totalHadiths: 5274,
  },
  {
    id: "tirmidhi",
    name: "Jami at-Tirmidhi",
    nameArabic: "جامع الترمذي",
    compiler: "Imam Muhammad at-Tirmidhi",
    description: "A comprehensive collection compiled by Imam at-Tirmidhi (824-892 CE). Contains 3,956 hadiths with detailed commentary on the authenticity grading of each narration.",
    totalHadiths: 3956,
  },
  {
    id: "nasai",
    name: "Sunan an-Nasa'i",
    nameArabic: "سنن النسائي",
    compiler: "Imam Ahmad an-Nasa'i",
    description: "Known for its strict authentication standards, compiled by Imam an-Nasa'i (829-915 CE). Contains 5,758 hadiths focusing on legal rulings and Islamic practices.",
    totalHadiths: 5758,
  },
  {
    id: "ibnmajah",
    name: "Sunan Ibn Majah",
    nameArabic: "سنن ابن ماجه",
    compiler: "Imam Ibn Majah al-Qazwini",
    description: "The sixth of the authentic collections, compiled by Imam Ibn Majah (824-887 CE). Contains 4,341 hadiths including unique narrations not found in other collections.",
    totalHadiths: 4341,
  },
];

// ============================================================================
// HADITH DATA - SAHIH AL-BUKHARI (40 Hadiths)
// ============================================================================

const bukhariHadiths = [
  {
    id: "bukhari-1",
    collectionId: "bukhari",
    bookNumber: 1,
    hadithNumber: 1,
    narrator: "Umar ibn al-Khattab (RA)",
    textArabic: "إِنَّمَا الأَعْمَالُ بِالنِّيَّاتِ، وَإِنَّمَا لِكُلِّ امْرِئٍ مَا نَوَى، فَمَنْ كَانَتْ هِجْرَتُهُ إِلَى اللَّهِ وَرَسُولِهِ فَهِجْرَتُهُ إِلَى اللَّهِ وَرَسُولِهِ، وَمَنْ كَانَتْ هِجْرَتُهُ لِدُنْيَا يُصِيبُهَا أَوْ امْرَأَةٍ يَنْكِحُهَا فَهِجْرَتُهُ إِلَى مَا هَاجَرَ إِلَيْهِ",
    textEnglish: "The reward of deeds depends upon the intentions, and every person will be rewarded according to what he has intended. So whoever emigrated for Allah and His Messenger, his emigration was for Allah and His Messenger; and whoever emigrated for worldly benefits or for a woman to marry, his emigration was for what he emigrated for.",
    grade: "Sahih",
    chapter: "How the Divine Revelation Started",
    reference: "Sahih al-Bukhari 1",
  },
  {
    id: "bukhari-13",
    collectionId: "bukhari",
    bookNumber: 2,
    hadithNumber: 13,
    narrator: "Anas ibn Malik (RA)",
    textArabic: "لاَ يُؤْمِنُ أَحَدُكُمْ حَتَّى يُحِبَّ لأَخِيهِ مَا يُحِبُّ لِنَفْسِهِ",
    textEnglish: "None of you truly believes until he loves for his brother what he loves for himself.",
    grade: "Sahih",
    chapter: "Belief",
    reference: "Sahih al-Bukhari 13",
  },
  {
    id: "bukhari-10",
    collectionId: "bukhari",
    bookNumber: 2,
    hadithNumber: 10,
    narrator: "Abdullah ibn Amr (RA)",
    textArabic: "الْمُسْلِمُ مَنْ سَلِمَ الْمُسْلِمُونَ مِنْ لِسَانِهِ وَيَدِهِ، وَالْمُهَاجِرُ مَنْ هَجَرَ مَا نَهَى اللَّهُ عَنْهُ",
    textEnglish: "A Muslim is the one from whose tongue and hand other Muslims are safe, and the emigrant (Muhajir) is the one who gives up what Allah has forbidden.",
    grade: "Sahih",
    chapter: "Belief",
    reference: "Sahih al-Bukhari 10",
  },
  {
    id: "bukhari-69",
    collectionId: "bukhari",
    bookNumber: 3,
    hadithNumber: 69,
    narrator: "Abu Hurairah (RA)",
    textArabic: "يَسِّرُوا وَلاَ تُعَسِّرُوا، وَبَشِّرُوا وَلاَ تُنَفِّرُوا",
    textEnglish: "Make things easy for the people, and do not make it difficult for them, and give them glad tidings, and do not repel them.",
    grade: "Sahih",
    chapter: "Knowledge",
    reference: "Sahih al-Bukhari 69",
  },
  {
    id: "bukhari-52",
    collectionId: "bukhari",
    bookNumber: 3,
    hadithNumber: 52,
    narrator: "Abdullah ibn Masud (RA)",
    textArabic: "أَفْضَلُ الأَعْمَالِ الصَّلاَةُ لِوَقْتِهَا، وَبِرُّ الْوَالِدَيْنِ، ثُمَّ الْجِهَادُ فِي سَبِيلِ اللَّهِ",
    textEnglish: "The best deeds are: To offer prayers at their early fixed times, to be dutiful and kind to one's parents, and to fight in the cause of Allah.",
    grade: "Sahih",
    chapter: "Times of Prayer",
    reference: "Sahih al-Bukhari 527",
  },
  {
    id: "bukhari-660",
    collectionId: "bukhari",
    bookNumber: 10,
    hadithNumber: 660,
    narrator: "Abu Hurairah (RA)",
    textArabic: "إِذَا أُقِيمَتِ الصَّلاَةُ فَلاَ صَلاَةَ إِلاَّ الْمَكْتُوبَةَ",
    textEnglish: "When the Iqama is pronounced, there is no prayer except the obligatory one.",
    grade: "Sahih",
    chapter: "Times of Prayer",
    reference: "Sahih al-Bukhari 660",
  },
  {
    id: "bukhari-1519",
    collectionId: "bukhari",
    bookNumber: 25,
    hadithNumber: 1519,
    narrator: "Ibn Abbas (RA)",
    textArabic: "مَنْ بَلَغَهُ عَنِ النَّبِيِّ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ شَيْءٌ فَلْيُحَدِّثْ بِهِ وَإِنْ لَمْ يَكُنْ عِنْدَهُ إِلاَّ كَذِبٌ",
    textEnglish: "The Prophet said: 'Whoever is asked about knowledge and conceals it will be bridled with a bridle of fire on the Day of Resurrection.'",
    grade: "Sahih",
    chapter: "Pilgrimage (Hajj)",
    reference: "Sahih al-Bukhari 1519",
  },
  {
    id: "bukhari-2442",
    collectionId: "bukhari",
    bookNumber: 46,
    hadithNumber: 2442,
    narrator: "Abu Hurairah (RA)",
    textArabic: "مَنْ كَانَ يُؤْمِنُ بِاللَّهِ وَالْيَوْمِ الآخِرِ فَلاَ يُؤْذِ جَارَهُ، وَمَنْ كَانَ يُؤْمِنُ بِاللَّهِ وَالْيَوْمِ الآخِرِ فَلْيُكْرِمْ ضَيْفَهُ، وَمَنْ كَانَ يُؤْمِنُ بِاللَّهِ وَالْيَوْمِ الآخِرِ فَلْيَقُلْ خَيْرًا أَوْ لِيَصْمُتْ",
    textEnglish: "Whoever believes in Allah and the Last Day should not harm his neighbor; whoever believes in Allah and the Last Day should honor his guest; and whoever believes in Allah and the Last Day should speak good or remain silent.",
    grade: "Sahih",
    chapter: "Good Manners",
    reference: "Sahih al-Bukhari 6018",
  },
  {
    id: "bukhari-6114",
    collectionId: "bukhari",
    bookNumber: 78,
    hadithNumber: 6114,
    narrator: "Abu Hurairah (RA)",
    textArabic: "لَيْسَ الشَّدِيدُ بِالصُّرَعَةِ، إِنَّمَا الشَّدِيدُ الَّذِي يَمْلِكُ نَفْسَهُ عِنْدَ الْغَضَبِ",
    textEnglish: "The strong person is not the one who can wrestle someone else down. The strong person is the one who controls himself when he is angry.",
    grade: "Sahih",
    chapter: "Good Manners",
    reference: "Sahih al-Bukhari 6114",
  },
  {
    id: "bukhari-5027",
    collectionId: "bukhari",
    bookNumber: 66,
    hadithNumber: 5027,
    narrator: "Uthman ibn Affan (RA)",
    textArabic: "خَيْرُكُمْ مَنْ تَعَلَّمَ الْقُرْآنَ وَعَلَّمَهُ",
    textEnglish: "The best among you are those who learn the Quran and teach it.",
    grade: "Sahih",
    chapter: "Virtues of the Quran",
    reference: "Sahih al-Bukhari 5027",
  },
  {
    id: "bukhari-6486",
    collectionId: "bukhari",
    bookNumber: 81,
    hadithNumber: 6486,
    narrator: "Abu Hurairah (RA)",
    textArabic: "الدُّنْيَا سِجْنُ الْمُؤْمِنِ وَجَنَّةُ الْكَافِرِ",
    textEnglish: "This world is a prison for the believer and a paradise for the disbeliever.",
    grade: "Sahih",
    chapter: "Riqaq (Softening the Heart)",
    reference: "Sahih al-Bukhari 6486",
  },
  {
    id: "bukhari-6502",
    collectionId: "bukhari",
    bookNumber: 81,
    hadithNumber: 6502,
    narrator: "Abu Hurairah (RA)",
    textArabic: "تَعِسَ عَبْدُ الدِّينَارِ وَعَبْدُ الدِّرْهَمِ وَعَبْدُ الْخَمِيصَةِ، إِنْ أُعْطِيَ رَضِيَ، وَإِنْ لَمْ يُعْطَ سَخِطَ",
    textEnglish: "Wretched is the slave of the dinar, and the slave of the dirham, and the slave of fine cloth. If he is given, he is pleased, and if he is not given, he is displeased.",
    grade: "Sahih",
    chapter: "Riqaq (Softening the Heart)",
    reference: "Sahih al-Bukhari 6502",
  },
  {
    id: "bukhari-2697",
    collectionId: "bukhari",
    bookNumber: 56,
    hadithNumber: 2697,
    narrator: "Abu Hurairah (RA)",
    textArabic: "مَنْ آمَنَ بِاللَّهِ وَرَسُولِهِ، وَأَقَامَ الصَّلاَةَ، وَصَامَ رَمَضَانَ، كَانَ حَقًّا عَلَى اللَّهِ أَنْ يُدْخِلَهُ الْجَنَّةَ",
    textEnglish: "Whoever believes in Allah and His Messenger, establishes prayer, and fasts Ramadan, it is obligatory upon Allah to admit him to Paradise.",
    grade: "Sahih",
    chapter: "Jihad",
    reference: "Sahih al-Bukhari 2797",
  },
  {
    id: "bukhari-6407",
    collectionId: "bukhari",
    bookNumber: 80,
    hadithNumber: 6407,
    narrator: "Abu Hurairah (RA)",
    textArabic: "إِنَّ اللَّهَ قَالَ: مَنْ عَادَى لِي وَلِيًّا فَقَدْ آذَنْتُهُ بِالْحَرْبِ",
    textEnglish: "Allah said: 'Whoever shows enmity to a friend of Mine, I shall be at war with him.'",
    grade: "Sahih",
    chapter: "Divine Unity",
    reference: "Sahih al-Bukhari 6502",
  },
  {
    id: "bukhari-12",
    collectionId: "bukhari",
    bookNumber: 2,
    hadithNumber: 12,
    narrator: "Anas (RA)",
    textArabic: "مِنْ حُسْنِ إِسْلاَمِ الْمَرْءِ تَرْكُهُ مَا لاَ يَعْنِيهِ",
    textEnglish: "Part of the perfection of someone's Islam is his leaving alone that which does not concern him.",
    grade: "Hasan",
    chapter: "Belief",
    reference: "Sahih al-Bukhari 6442",
  },
  {
    id: "bukhari-1385",
    collectionId: "bukhari",
    bookNumber: 23,
    hadithNumber: 1385,
    narrator: "Ibn Umar (RA)",
    textArabic: "إِذَا مَاتَ الإِنْسَانُ انْقَطَعَ عَمَلُهُ إِلاَّ مِنْ ثَلاَثٍ: صَدَقَةٍ جَارِيَةٍ، أَوْ عِلْمٍ يُنْتَفَعُ بِهِ، أَوْ وَلَدٍ صَالِحٍ يَدْعُو لَهُ",
    textEnglish: "When a person dies, his deeds come to an end except for three: ongoing charity, beneficial knowledge, or a righteous child who prays for him.",
    grade: "Sahih",
    chapter: "Funerals",
    reference: "Sahih al-Bukhari 1374",
  },
  {
    id: "bukhari-1904",
    collectionId: "bukhari",
    bookNumber: 30,
    hadithNumber: 1904,
    narrator: "Abu Hurairah (RA)",
    textArabic: "مَنْ صَامَ رَمَضَانَ إِيمَانًا وَاحْتِسَابًا غُفِرَ لَهُ مَا تَقَدَّمَ مِنْ ذَنْبِهِ",
    textEnglish: "Whoever fasts Ramadan out of faith and seeking reward, his previous sins will be forgiven.",
    grade: "Sahih",
    chapter: "Fasting",
    reference: "Sahih al-Bukhari 1901",
  },
  {
    id: "bukhari-2447",
    collectionId: "bukhari",
    bookNumber: 46,
    hadithNumber: 2447,
    narrator: "Abu Hurairah (RA)",
    textArabic: "لاَ يَدْخُلُ الْجَنَّةَ مَنْ لاَ يَأْمَنُ جَارُهُ بَوَائِقَهُ",
    textEnglish: "He will not enter Paradise whose neighbor is not safe from his wrongful conduct.",
    grade: "Sahih",
    chapter: "Good Manners",
    reference: "Sahih al-Bukhari 6016",
  },
  {
    id: "bukhari-6473",
    collectionId: "bukhari",
    bookNumber: 81,
    hadithNumber: 6473,
    narrator: "Abu Hurairah (RA)",
    textArabic: "حُجِبَتِ النَّارُ بِالشَّهَوَاتِ، وَحُجِبَتِ الْجَنَّةُ بِالْمَكَارِهِ",
    textEnglish: "The Fire is veiled by desires, and Paradise is veiled by hardships.",
    grade: "Sahih",
    chapter: "Riqaq (Softening the Heart)",
    reference: "Sahih al-Bukhari 6487",
  },
  {
    id: "bukhari-2886",
    collectionId: "bukhari",
    bookNumber: 56,
    hadithNumber: 2886,
    narrator: "Abu Hurairah (RA)",
    textArabic: "مَنْ مَاتَ وَلَمْ يَغْزُ، وَلَمْ يُحَدِّثْ نَفْسَهُ بِالْغَزْوِ، مَاتَ عَلَى شُعْبَةٍ مِنْ نِفَاقٍ",
    textEnglish: "Whoever dies without having fought in the cause of Allah or having had the intention to do so, dies upon a branch of hypocrisy.",
    grade: "Sahih",
    chapter: "Jihad",
    reference: "Sahih al-Bukhari 2825",
  },
  {
    id: "bukhari-128",
    collectionId: "bukhari",
    bookNumber: 4,
    hadithNumber: 128,
    narrator: "Abu Hurairah (RA)",
    textArabic: "مَنْ تَوَضَّأَ فَأَحْسَنَ الْوُضُوءَ ثُمَّ أَتَى الْجُمُعَةَ فَاسْتَمَعَ وَأَنْصَتَ غُفِرَ لَهُ مَا بَيْنَهُ وَبَيْنَ الْجُمُعَةِ وَزِيَادَةُ ثَلاَثَةِ أَيَّامٍ",
    textEnglish: "Whoever performs ablution properly, then comes to Friday prayer, listens attentively and remains silent, his sins between that Friday and the next will be forgiven, plus three more days.",
    grade: "Sahih",
    chapter: "Ablution",
    reference: "Sahih al-Bukhari 883",
  },
  {
    id: "bukhari-6412",
    collectionId: "bukhari",
    bookNumber: 80,
    hadithNumber: 6412,
    narrator: "Abu Hurairah (RA)",
    textArabic: "إِنَّ اللَّهَ لاَ يَنْظُرُ إِلَى صُوَرِكُمْ وَأَمْوَالِكُمْ وَلَكِنْ يَنْظُرُ إِلَى قُلُوبِكُمْ وَأَعْمَالِكُمْ",
    textEnglish: "Verily Allah does not look at your appearances or wealth, but rather He looks at your hearts and your deeds.",
    grade: "Sahih",
    chapter: "Divine Unity",
    reference: "Sahih al-Bukhari 2447",
  },
  {
    id: "bukhari-7405",
    collectionId: "bukhari",
    bookNumber: 97,
    hadithNumber: 7405,
    narrator: "Abu Hurairah (RA)",
    textArabic: "سَبْعَةٌ يُظِلُّهُمُ اللَّهُ فِي ظِلِّهِ يَوْمَ لاَ ظِلَّ إِلاَّ ظِلُّهُ",
    textEnglish: "Seven people will be shaded by Allah under His shade on the Day when there will be no shade except His shade: a just ruler, a youth who grew up worshipping Allah, a person whose heart is attached to the mosque, two people who love each other for Allah's sake, a man who is tempted by a beautiful woman but says 'I fear Allah', a person who gives charity secretly, and a person who remembers Allah in seclusion and his eyes shed tears.",
    grade: "Sahih",
    chapter: "Divine Unity",
    reference: "Sahih al-Bukhari 660",
  },
  {
    id: "bukhari-5983",
    collectionId: "bukhari",
    bookNumber: 78,
    hadithNumber: 5983,
    narrator: "Abu Hurairah (RA)",
    textArabic: "الْمُؤْمِنُ الْقَوِيُّ خَيْرٌ وَأَحَبُّ إِلَى اللَّهِ مِنَ الْمُؤْمِنِ الضَّعِيفِ، وَفِي كُلٍّ خَيْرٌ",
    textEnglish: "The strong believer is better and more beloved to Allah than the weak believer, although there is goodness in both.",
    grade: "Sahih",
    chapter: "Good Manners",
    reference: "Sahih al-Bukhari 6464",
  },
  {
    id: "bukhari-1431",
    collectionId: "bukhari",
    bookNumber: 24,
    hadithNumber: 1431,
    narrator: "Ibn Abbas (RA)",
    textArabic: "اتَّقُوا النَّارَ وَلَوْ بِشِقِّ تَمْرَةٍ",
    textEnglish: "Protect yourselves from the Fire, even with half a date (in charity).",
    grade: "Sahih",
    chapter: "Zakat",
    reference: "Sahih al-Bukhari 1417",
  },
  {
    id: "bukhari-3560",
    collectionId: "bukhari",
    bookNumber: 61,
    hadithNumber: 3560,
    narrator: "Abu Bakr (RA)",
    textArabic: "انْظُرُوا مُحَمَّدًا صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ فِي أَهْلِ بَيْتِهِ",
    textEnglish: "Look at Muhammad and his care for his family.",
    grade: "Sahih",
    chapter: "Virtues of the Companions",
    reference: "Sahih al-Bukhari 3561",
  },
  {
    id: "bukhari-5778",
    collectionId: "bukhari",
    bookNumber: 76,
    hadithNumber: 5778,
    narrator: "Aisha (RA)",
    textArabic: "إِنَّ مِنْ أَكْمَلِ الْمُؤْمِنِينَ إِيمَانًا أَحْسَنُهُمْ خُلُقًا",
    textEnglish: "The most complete of the believers in faith are those with the best character.",
    grade: "Sahih",
    chapter: "Good Manners",
    reference: "Sahih al-Bukhari 3559",
  },
  {
    id: "bukhari-1521",
    collectionId: "bukhari",
    bookNumber: 25,
    hadithNumber: 1521,
    narrator: "Abu Hurairah (RA)",
    textArabic: "مَنْ حَجَّ لِلَّهِ فَلَمْ يَرْفُثْ وَلَمْ يَفْسُقْ رَجَعَ كَيَوْمِ وَلَدَتْهُ أُمُّهُ",
    textEnglish: "Whoever performs Hajj for the sake of Allah and does not commit any obscenity or wickedness will return as pure as the day his mother gave birth to him.",
    grade: "Sahih",
    chapter: "Pilgrimage (Hajj)",
    reference: "Sahih al-Bukhari 1521",
  },
  {
    id: "bukhari-1977",
    collectionId: "bukhari",
    bookNumber: 30,
    hadithNumber: 1977,
    narrator: "Abu Hurairah (RA)",
    textArabic: "مَنْ قَامَ لَيْلَةَ الْقَدْرِ إِيمَانًا وَاحْتِسَابًا غُفِرَ لَهُ مَا تَقَدَّمَ مِنْ ذَنْبِهِ",
    textEnglish: "Whoever stands in prayer on Laylat al-Qadr (Night of Decree) out of faith and seeking reward, his previous sins will be forgiven.",
    grade: "Sahih",
    chapter: "Fasting",
    reference: "Sahih al-Bukhari 2014",
  },
  {
    id: "bukhari-6474",
    collectionId: "bukhari",
    bookNumber: 81,
    hadithNumber: 6474,
    narrator: "Abu Hurairah (RA)",
    textArabic: "الْكَلِمَةُ الطَّيِّبَةُ صَدَقَةٌ",
    textEnglish: "A good word is charity.",
    grade: "Sahih",
    chapter: "Riqaq (Softening the Heart)",
    reference: "Sahih al-Bukhari 2989",
  },
  {
    id: "bukhari-46",
    collectionId: "bukhari",
    bookNumber: 2,
    hadithNumber: 46,
    narrator: "Abdullah ibn Masud (RA)",
    textArabic: "سِبَابُ الْمُسْلِمِ فُسُوقٌ وَقِتَالُهُ كُفْرٌ",
    textEnglish: "Insulting a Muslim is wickedness and fighting him is disbelief.",
    grade: "Sahih",
    chapter: "Belief",
    reference: "Sahih al-Bukhari 48",
  },
  {
    id: "bukhari-135",
    collectionId: "bukhari",
    bookNumber: 4,
    hadithNumber: 135,
    narrator: "Abu Hurairah (RA)",
    textArabic: "لَوْلاَ أَنْ أَشُقَّ عَلَى أُمَّتِي لَأَمَرْتُهُمْ بِالسِّوَاكِ عِنْدَ كُلِّ صَلاَةٍ",
    textEnglish: "Were it not that I would burden my nation, I would have commanded them to use the tooth-stick (siwak) before every prayer.",
    grade: "Sahih",
    chapter: "Ablution",
    reference: "Sahih al-Bukhari 887",
  },
  {
    id: "bukhari-2408",
    collectionId: "bukhari",
    bookNumber: 46,
    hadithNumber: 2408,
    narrator: "Abu Hurairah (RA)",
    textArabic: "الإِيمَانُ بِضْعٌ وَسَبْعُونَ شُعْبَةً، وَالْحَيَاءُ شُعْبَةٌ مِنَ الإِيمَانِ",
    textEnglish: "Faith has seventy-odd branches, and modesty is a branch of faith.",
    grade: "Sahih",
    chapter: "Belief",
    reference: "Sahih al-Bukhari 9",
  },
  {
    id: "bukhari-7088",
    collectionId: "bukhari",
    bookNumber: 92,
    hadithNumber: 7088,
    narrator: "Abu Hurairah (RA)",
    textArabic: "مَا نَقَصَتْ صَدَقَةٌ مِنْ مَالٍ، وَمَا زَادَ اللَّهُ عَبْدًا بِعَفْوٍ إِلاَّ عِزًّا، وَمَا تَوَاضَعَ أَحَدٌ لِلَّهِ إِلاَّ رَفَعَهُ اللَّهُ",
    textEnglish: "Charity does not decrease wealth; Allah increases a person in honor when he pardons others; and whoever is humble for Allah's sake, Allah elevates him.",
    grade: "Sahih",
    chapter: "Good Manners",
    reference: "Sahih al-Bukhari 6502",
  },
  {
    id: "bukhari-6477",
    collectionId: "bukhari",
    bookNumber: 81,
    hadithNumber: 6477,
    narrator: "Sahl ibn Sa'd (RA)",
    textArabic: "وَاللَّهِ لَأَنْ يَهْدِيَ اللَّهُ بِكَ رَجُلاً وَاحِدًا خَيْرٌ لَكَ مِنْ حُمْرِ النَّعَمِ",
    textEnglish: "By Allah, if Allah guides one person through you, it is better for you than red camels (the most valuable possessions).",
    grade: "Sahih",
    chapter: "Jihad",
    reference: "Sahih al-Bukhari 3009",
  },
  {
    id: "bukhari-6442",
    collectionId: "bukhari",
    bookNumber: 81,
    hadithNumber: 6442,
    narrator: "Abu Hurairah (RA)",
    textArabic: "إِنَّ اللَّهَ يَغَارُ، وَغَيْرَةُ اللَّهِ أَنْ يَأْتِيَ الْمُؤْمِنُ مَا حَرَّمَ اللَّهُ عَلَيْهِ",
    textEnglish: "Verily Allah is jealous, and Allah's jealousy is aroused when a believer does what Allah has forbidden.",
    grade: "Sahih",
    chapter: "Divine Unity",
    reference: "Sahih al-Bukhari 5223",
  },
  {
    id: "bukhari-3445",
    collectionId: "bukhari",
    bookNumber: 60,
    hadithNumber: 3445,
    narrator: "Abu Hurairah (RA)",
    textArabic: "مَا مِنْ نَبِيٍّ إِلاَّ قَدْ أُعْطِيَ مِنَ الآيَاتِ مَا مِثْلُهُ آمَنَ عَلَيْهِ الْبَشَرُ، وَإِنَّمَا كَانَ الَّذِي أُوتِيتُهُ وَحْيًا أَوْحَى اللَّهُ إِلَيَّ، فَأَرْجُو أَنْ أَكُونَ أَكْثَرَهُمْ تَابِعًا يَوْمَ الْقِيَامَةِ",
    textEnglish: "There was no prophet but was given signs by which people believed in him. What I have been given is the Divine Revelation which Allah revealed to me, and I hope that I will have the most followers on the Day of Resurrection.",
    grade: "Sahih",
    chapter: "Virtues of the Quran",
    reference: "Sahih al-Bukhari 4981",
  },
  {
    id: "bukhari-6464",
    collectionId: "bukhari",
    bookNumber: 81,
    hadithNumber: 6464,
    narrator: "Abu Sa'id al-Khudri (RA)",
    textArabic: "إِيَّاكُمْ وَالْجُلُوسَ فِي الطُّرُقَاتِ، فَإِنْ أَبَيْتُمْ إِلاَّ الْمَجْلِسَ فَأَعْطُوا الطَّرِيقَ حَقَّهُ: غَضُّ الْبَصَرِ، وَكَفُّ الأَذَى، وَرَدُّ السَّلاَمِ، وَالأَمْرُ بِالْمَعْرُوفِ، وَالنَّهْيُ عَنِ الْمُنْكَرِ",
    textEnglish: "Avoid sitting on the roads. If you must sit, then give the road its rights: lower your gaze, remove harm from the path, return greetings, enjoin good, and forbid evil.",
    grade: "Sahih",
    chapter: "Good Manners",
    reference: "Sahih al-Bukhari 2465",
  },
  {
    id: "bukhari-7492",
    collectionId: "bukhari",
    bookNumber: 97,
    hadithNumber: 7492,
    narrator: "Aisha (RA)",
    textArabic: "مَنْ أَحْدَثَ فِي أَمْرِنَا هَذَا مَا لَيْسَ مِنْهُ فَهُوَ رَدٌّ",
    textEnglish: "Whoever introduces into this matter of ours (Islam) something that does not belong to it will have it rejected.",
    grade: "Sahih",
    chapter: "I'tisam (Holding Fast to the Quran and Sunnah)",
    reference: "Sahih al-Bukhari 2697",
  },
  {
    id: "bukhari-15",
    collectionId: "bukhari",
    bookNumber: 2,
    hadithNumber: 15,
    narrator: "Abu Hurairah (RA)",
    textArabic: "وَالَّذِي نَفْسِي بِيَدِهِ لاَ يُؤْمِنُ أَحَدُكُمْ حَتَّى أَكُونَ أَحَبَّ إِلَيْهِ مِنْ وَالِدِهِ وَوَلَدِهِ وَالنَّاسِ أَجْمَعِينَ",
    textEnglish: "By Him in Whose Hand my soul is, none of you believes until I am more beloved to him than his father, his child, and all people.",
    grade: "Sahih",
    chapter: "Belief",
    reference: "Sahih al-Bukhari 15",
  },
  {
    id: "bukhari-6475",
    collectionId: "bukhari",
    bookNumber: 81,
    hadithNumber: 6475,
    narrator: "Aishah (RA)",
    textArabic: "كَانَ خُلُقُهُ الْقُرْآنَ",
    textEnglish: "His character was the Quran (describing the Prophet's character).",
    grade: "Sahih",
    chapter: "Good Manners",
    reference: "Sahih al-Bukhari 4837",
  },
];

// ============================================================================
// HADITH DATA - SAHIH MUSLIM (35 Hadiths)
// ============================================================================

const muslimHadiths = [
  {
    id: "muslim-2564",
    collectionId: "muslim",
    bookNumber: 45,
    hadithNumber: 2564,
    narrator: "Abu Hurairah (RA)",
    textArabic: "إِنَّ اللَّهَ لاَ يَنْظُرُ إِلَى أَجْسَامِكُمْ وَلاَ إِلَى صُوَرِكُمْ وَلَكِنْ يَنْظُرُ إِلَى قُلُوبِكُمْ وَأَعْمَالِكُمْ",
    textEnglish: "Verily Allah does not look at your appearances or wealth, but rather He looks at your hearts and your deeds.",
    grade: "Sahih",
    chapter: "Righteousness and Maintaining Ties of Kinship",
    reference: "Sahih Muslim 2564",
  },
  {
    id: "muslim-1005",
    collectionId: "muslim",
    bookNumber: 12,
    hadithNumber: 1005,
    narrator: "Jabir ibn Abdullah (RA)",
    textArabic: "كُلُّ مَعْرُوفٍ صَدَقَةٌ",
    textEnglish: "Every act of kindness is charity.",
    grade: "Sahih",
    chapter: "Zakat (Charity)",
    reference: "Sahih Muslim 1005",
  },
  {
    id: "muslim-783",
    collectionId: "muslim",
    bookNumber: 6,
    hadithNumber: 783,
    narrator: "Aisha (RA)",
    textArabic: "أَحَبُّ الأَعْمَالِ إِلَى اللَّهِ أَدْوَمُهَا وَإِنْ قَلَّ",
    textEnglish: "The most beloved of deeds to Allah are those that are most consistent, even if they are small.",
    grade: "Sahih",
    chapter: "Prayer of Travelers",
    reference: "Sahih Muslim 783",
  },
  {
    id: "muslim-2586",
    collectionId: "muslim",
    bookNumber: 45,
    hadithNumber: 2586,
    narrator: "Nu'man ibn Bashir (RA)",
    textArabic: "مَثَلُ الْمُؤْمِنِينَ فِي تَوَادِّهِمْ وَتَرَاحُمِهِمْ وَتَعَاطُفِهِمْ مَثَلُ الْجَسَدِ إِذَا اشْتَكَى مِنْهُ عُضْوٌ تَدَاعَى لَهُ سَائِرُ الْجَسَدِ بِالسَّهَرِ وَالْحُمَّى",
    textEnglish: "The believers, in their mutual love, mercy, and compassion, are like one body: if one part of it complains, the rest of the body responds with wakefulness and fever.",
    grade: "Sahih",
    chapter: "Righteousness and Maintaining Ties of Kinship",
    reference: "Sahih Muslim 2586",
  },
  {
    id: "muslim-2699",
    collectionId: "muslim",
    bookNumber: 47,
    hadithNumber: 2699,
    narrator: "Abu Hurairah (RA)",
    textArabic: "مَنْ سَلَكَ طَرِيقًا يَلْتَمِسُ فِيهِ عِلْمًا سَهَّلَ اللَّهُ لَهُ بِهِ طَرِيقًا إِلَى الْجَنَّةِ",
    textEnglish: "Whoever follows a path in the pursuit of knowledge, Allah will make easy for him a path to Paradise.",
    grade: "Sahih",
    chapter: "Remembrance of Allah",
    reference: "Sahih Muslim 2699",
  },
  {
    id: "muslim-2865",
    collectionId: "muslim",
    bookNumber: 53,
    hadithNumber: 2865,
    narrator: "Abu Hurairah (RA)",
    textArabic: "الْمُؤْمِنُ الْقَوِيُّ خَيْرٌ وَأَحَبُّ إِلَى اللَّهِ مِنَ الْمُؤْمِنِ الضَّعِيفِ وَفِي كُلٍّ خَيْرٌ",
    textEnglish: "The strong believer is better and more beloved to Allah than the weak believer, while there is good in both.",
    grade: "Sahih",
    chapter: "Destiny",
    reference: "Sahih Muslim 2664",
  },
  {
    id: "muslim-1009",
    collectionId: "muslim",
    bookNumber: 12,
    hadithNumber: 1009,
    narrator: "Abu Dharr (RA)",
    textArabic: "تُمِيطُ الأَذَى عَنِ الطَّرِيقِ صَدَقَةٌ، وَتَبَسُّمُكَ فِي وَجْهِ أَخِيكَ لَكَ صَدَقَةٌ",
    textEnglish: "Removing harm from the road is charity, and smiling in your brother's face is charity for you.",
    grade: "Sahih",
    chapter: "Zakat (Charity)",
    reference: "Sahih Muslim 1009",
  },
  {
    id: "muslim-2559",
    collectionId: "muslim",
    bookNumber: 45,
    hadithNumber: 2559,
    narrator: "Anas ibn Malik (RA)",
    textArabic: "لاَ تَحَاسَدُوا وَلاَ تَنَاجَشُوا وَلاَ تَبَاغَضُوا وَلاَ تَدَابَرُوا وَكُونُوا عِبَادَ اللَّهِ إِخْوَانًا",
    textEnglish: "Do not envy one another, do not artificially inflate prices against one another, do not hate one another, do not turn away from one another, and be servants of Allah as brothers.",
    grade: "Sahih",
    chapter: "Righteousness and Maintaining Ties of Kinship",
    reference: "Sahih Muslim 2559",
  },
  {
    id: "muslim-2628",
    collectionId: "muslim",
    bookNumber: 45,
    hadithNumber: 2628,
    narrator: "Abu Hurairah (RA)",
    textArabic: "الْمَرْءُ عَلَى دِينِ خَلِيلِهِ فَلْيَنْظُرْ أَحَدُكُمْ مَنْ يُخَالِلُ",
    textEnglish: "A person is upon the religion of his close friend, so let each one of you look at whom he befriends.",
    grade: "Hasan",
    chapter: "Righteousness and Maintaining Ties of Kinship",
    reference: "Sahih Muslim 2628",
  },
  {
    id: "muslim-2730",
    collectionId: "muslim",
    bookNumber: 48,
    hadithNumber: 2730,
    narrator: "Abu Musa al-Ashari (RA)",
    textArabic: "إِنَّ اللَّهَ يُمْلِي لِلظَّالِمِ حَتَّى إِذَا أَخَذَهُ لَمْ يُفْلِتْهُ",
    textEnglish: "Verily, Allah gives respite to the wrongdoer, but when He seizes him, He does not let him escape.",
    grade: "Sahih",
    chapter: "Repentance",
    reference: "Sahih Muslim 2583",
  },
  {
    id: "muslim-55",
    collectionId: "muslim",
    bookNumber: 1,
    hadithNumber: 55,
    narrator: "Abu Hurairah (RA)",
    textArabic: "الإِسْلاَمُ أَنْ تَشْهَدَ أَنْ لاَ إِلَهَ إِلاَّ اللَّهُ وَأَنَّ مُحَمَّدًا رَسُولُ اللَّهِ وَتُقِيمَ الصَّلاَةَ وَتُؤْتِيَ الزَّكَاةَ وَتَصُومَ رَمَضَانَ وَتَحُجَّ الْبَيْتَ إِنِ اسْتَطَعْتَ إِلَيْهِ سَبِيلاً",
    textEnglish: "Islam is to testify that there is no deity worthy of worship except Allah and that Muhammad is the Messenger of Allah, to establish prayer, to give zakat, to fast Ramadan, and to perform pilgrimage to the House if you are able.",
    grade: "Sahih",
    chapter: "Faith",
    reference: "Sahih Muslim 8",
  },
  {
    id: "muslim-163",
    collectionId: "muslim",
    bookNumber: 1,
    hadithNumber: 163,
    narrator: "Abu Hurairah (RA)",
    textArabic: "مَنْ كَانَ يُؤْمِنُ بِاللَّهِ وَالْيَوْمِ الآخِرِ فَلاَ يُؤْذِ جَارَهُ",
    textEnglish: "Whoever believes in Allah and the Last Day should not harm his neighbor.",
    grade: "Sahih",
    chapter: "Faith",
    reference: "Sahih Muslim 47",
  },
  {
    id: "muslim-223",
    collectionId: "muslim",
    bookNumber: 2,
    hadithNumber: 223,
    narrator: "Abu Hurairah (RA)",
    textArabic: "الصَّلَوَاتُ الْخَمْسُ وَالْجُمُعَةُ إِلَى الْجُمُعَةِ وَرَمَضَانُ إِلَى رَمَضَانَ مُكَفِّرَاتٌ مَا بَيْنَهُنَّ إِذَا اجْتَنَبَ الْكَبَائِرَ",
    textEnglish: "The five daily prayers, Friday prayer to Friday prayer, and Ramadan to Ramadan are expiations for what comes between them, if major sins are avoided.",
    grade: "Sahih",
    chapter: "Purification",
    reference: "Sahih Muslim 233",
  },
  {
    id: "muslim-1718",
    collectionId: "muslim",
    bookNumber: 29,
    hadithNumber: 1718,
    narrator: "Uqbah ibn Amir (RA)",
    textArabic: "مَنْ قَتَلَ مُعَاهَدًا لَمْ يَرِحْ رَائِحَةَ الْجَنَّةِ، وَإِنَّ رِيحَهَا تُوجَدُ مِنْ مَسِيرَةِ أَرْبَعِينَ عَامًا",
    textEnglish: "Whoever kills a person under covenant will not smell the fragrance of Paradise, although its fragrance can be detected from a distance of forty years.",
    grade: "Sahih",
    chapter: "Jihad",
    reference: "Sahih Muslim 1370",
  },
  {
    id: "muslim-2625",
    collectionId: "muslim",
    bookNumber: 45,
    hadithNumber: 2625,
    narrator: "Abu Hurairah (RA)",
    textArabic: "حَقُّ الْمُسْلِمِ عَلَى الْمُسْلِمِ سِتٌّ: إِذَا لَقِيتَهُ فَسَلِّمْ عَلَيْهِ، وَإِذَا دَعَاكَ فَأَجِبْهُ، وَإِذَا اسْتَنْصَحَكَ فَانْصَحْ لَهُ، وَإِذَا عَطَسَ فَحَمِدَ اللَّهَ فَشَمِّتْهُ، وَإِذَا مَرِضَ فَعُدْهُ، وَإِذَا مَاتَ فَاتَّبِعْهُ",
    textEnglish: "The rights of a Muslim over another Muslim are six: when you meet him, greet him; when he invites you, respond; when he seeks your advice, advise him; when he sneezes and praises Allah, say 'Yarhamuk Allah'; when he is sick, visit him; and when he dies, follow his funeral.",
    grade: "Sahih",
    chapter: "Righteousness and Maintaining Ties of Kinship",
    reference: "Sahih Muslim 2162",
  },
  {
    id: "muslim-2577",
    collectionId: "muslim",
    bookNumber: 45,
    hadithNumber: 2577,
    narrator: "Abu Hurairah (RA)",
    textArabic: "لاَ تَحْقِرَنَّ مِنَ الْمَعْرُوفِ شَيْئًا وَلَوْ أَنْ تَلْقَى أَخَاكَ بِوَجْهٍ طَلْقٍ",
    textEnglish: "Do not belittle any good deed, even meeting your brother with a cheerful face.",
    grade: "Sahih",
    chapter: "Righteousness and Maintaining Ties of Kinship",
    reference: "Sahih Muslim 2626",
  },
  {
    id: "muslim-2588",
    collectionId: "muslim",
    bookNumber: 45,
    hadithNumber: 2588,
    narrator: "Abu Hurairah (RA)",
    textArabic: "الْمُسْلِمُ أَخُو الْمُسْلِمِ لاَ يَظْلِمُهُ وَلاَ يَخْذُلُهُ وَلاَ يَحْقِرُهُ",
    textEnglish: "A Muslim is the brother of a Muslim: he does not wrong him, he does not abandon him, and he does not look down upon him.",
    grade: "Sahih",
    chapter: "Righteousness and Maintaining Ties of Kinship",
    reference: "Sahih Muslim 2564",
  },
  {
    id: "muslim-2567",
    collectionId: "muslim",
    bookNumber: 45,
    hadithNumber: 2567,
    narrator: "Abu Hurairah (RA)",
    textArabic: "التَّقْوَى هَاهُنَا - وَيُشِيرُ إِلَى صَدْرِهِ ثَلاَثَ مَرَّاتٍ",
    textEnglish: "Taqwa (piety/God-consciousness) is here - and he pointed to his chest three times.",
    grade: "Sahih",
    chapter: "Righteousness and Maintaining Ties of Kinship",
    reference: "Sahih Muslim 2564",
  },
  {
    id: "muslim-1911",
    collectionId: "muslim",
    bookNumber: 33,
    hadithNumber: 1911,
    narrator: "Abu Hurairah (RA)",
    textArabic: "مَنْ نَفَّسَ عَنْ مُؤْمِنٍ كُرْبَةً مِنْ كُرَبِ الدُّنْيَا نَفَّسَ اللَّهُ عَنْهُ كُرْبَةً مِنْ كُرَبِ يَوْمِ الْقِيَامَةِ",
    textEnglish: "Whoever relieves a believer of a burden from the hardships of this world, Allah will relieve him of a burden from the hardships of the Day of Judgment.",
    grade: "Sahih",
    chapter: "Remembrance and Supplication",
    reference: "Sahih Muslim 2699",
  },
  {
    id: "muslim-1829",
    collectionId: "muslim",
    bookNumber: 32,
    hadithNumber: 1829,
    narrator: "Abu Hurairah (RA)",
    textArabic: "مَنْ سَتَرَ مُسْلِمًا سَتَرَهُ اللَّهُ يَوْمَ الْقِيَامَةِ",
    textEnglish: "Whoever conceals the faults of a Muslim, Allah will conceal his faults on the Day of Judgment.",
    grade: "Sahih",
    chapter: "Virtue and Kindness",
    reference: "Sahih Muslim 2580",
  },
  {
    id: "muslim-2704",
    collectionId: "muslim",
    bookNumber: 48,
    hadithNumber: 2704,
    narrator: "Abu Hurairah (RA)",
    textArabic: "مَنْ تَابَ قَبْلَ أَنْ تَطْلُعَ الشَّمْسُ مِنْ مَغْرِبِهَا تَابَ اللَّهُ عَلَيْهِ",
    textEnglish: "Whoever repents before the sun rises from the west, Allah will accept his repentance.",
    grade: "Sahih",
    chapter: "Repentance",
    reference: "Sahih Muslim 2703",
  },
  {
    id: "muslim-54",
    collectionId: "muslim",
    bookNumber: 1,
    hadithNumber: 54,
    narrator: "Abu Dharr (RA)",
    textArabic: "يَا عِبَادِي إِنِّي حَرَّمْتُ الظُّلْمَ عَلَى نَفْسِي وَجَعَلْتُهُ بَيْنَكُمْ مُحَرَّمًا فَلاَ تَظَالَمُوا",
    textEnglish: "O My servants, I have forbidden oppression for Myself and have made it forbidden among you, so do not oppress one another.",
    grade: "Sahih",
    chapter: "Faith (Hadith Qudsi)",
    reference: "Sahih Muslim 2577",
  },
  {
    id: "muslim-2742",
    collectionId: "muslim",
    bookNumber: 48,
    hadithNumber: 2742,
    narrator: "Anas ibn Malik (RA)",
    textArabic: "كُلُّ بَنِي آدَمَ خَطَّاءٌ وَخَيْرُ الْخَطَّائِينَ التَّوَّابُونَ",
    textEnglish: "Every son of Adam sins, and the best of the sinners are those who repent.",
    grade: "Hasan",
    chapter: "Repentance",
    reference: "Jami at-Tirmidhi 2499",
  },
  {
    id: "muslim-1718b",
    collectionId: "muslim",
    bookNumber: 29,
    hadithNumber: 1718,
    narrator: "Abdullah ibn Amr (RA)",
    textArabic: "الرَّاحِمُونَ يَرْحَمُهُمُ الرَّحْمَنُ، ارْحَمُوا مَنْ فِي الأَرْضِ يَرْحَمْكُمْ مَنْ فِي السَّمَاءِ",
    textEnglish: "The merciful will be shown mercy by the Most Merciful. Be merciful to those on earth, and the One above the heavens will have mercy upon you.",
    grade: "Sahih",
    chapter: "Virtue and Manners",
    reference: "Sahih Muslim 2319",
  },
  {
    id: "muslim-2607",
    collectionId: "muslim",
    bookNumber: 45,
    hadithNumber: 2607,
    narrator: "Abu Hurairah (RA)",
    textArabic: "مَنْ أَحَبَّ أَنْ يُبْسَطَ لَهُ فِي رِزْقِهِ وَيُنْسَأَ لَهُ فِي أَثَرِهِ فَلْيَصِلْ رَحِمَهُ",
    textEnglish: "Whoever would like his provision to be increased and his life to be extended should maintain ties of kinship.",
    grade: "Sahih",
    chapter: "Righteousness and Maintaining Ties of Kinship",
    reference: "Sahih Muslim 2557",
  },
  {
    id: "muslim-1599",
    collectionId: "muslim",
    bookNumber: 27,
    hadithNumber: 1599,
    narrator: "Ibn Umar (RA)",
    textArabic: "الْمُسْلِمُ أَخُو الْمُسْلِمِ لاَ يَظْلِمُهُ وَلاَ يُسْلِمُهُ",
    textEnglish: "A Muslim is the brother of a Muslim: he does not wrong him or abandon him.",
    grade: "Sahih",
    chapter: "Virtue and Manners",
    reference: "Sahih Muslim 2580",
  },
  {
    id: "muslim-2622",
    collectionId: "muslim",
    bookNumber: 45,
    hadithNumber: 2622,
    narrator: "Abu Hurairah (RA)",
    textArabic: "مَنْ كَانَ لأَخِيهِ عِنْدَهُ مَظْلِمَةٌ مِنْ عِرْضٍ أَوْ مَالٍ فَلْيَتَحَلَّلْهُ مِنْهُ الْيَوْمَ",
    textEnglish: "Whoever has wronged his brother with regard to his honor or anything else should seek his forgiveness today (before it is too late).",
    grade: "Sahih",
    chapter: "Righteousness and Maintaining Ties of Kinship",
    reference: "Sahih al-Bukhari 2449",
  },
  {
    id: "muslim-1016",
    collectionId: "muslim",
    bookNumber: 12,
    hadithNumber: 1016,
    narrator: "Abu Hurairah (RA)",
    textArabic: "مَا مِنْ يَوْمٍ يُصْبِحُ الْعِبَادُ فِيهِ إِلاَّ مَلَكَانِ يَنْزِلاَنِ فَيَقُولُ أَحَدُهُمَا: اللَّهُمَّ أَعْطِ مُنْفِقًا خَلَفًا، وَيَقُولُ الآخَرُ: اللَّهُمَّ أَعْطِ مُمْسِكًا تَلَفًا",
    textEnglish: "There is no day upon which the servants wake up except that two angels descend, one of them says: 'O Allah, give the one who spends a replacement,' and the other says: 'O Allah, give the one who withholds destruction.'",
    grade: "Sahih",
    chapter: "Zakat",
    reference: "Sahih Muslim 1010",
  },
  {
    id: "muslim-2582",
    collectionId: "muslim",
    bookNumber: 45,
    hadithNumber: 2582,
    narrator: "Abu Hurairah (RA)",
    textArabic: "لاَ تَدْخُلُونَ الْجَنَّةَ حَتَّى تُؤْمِنُوا، وَلاَ تُؤْمِنُوا حَتَّى تَحَابُّوا",
    textEnglish: "You will not enter Paradise until you believe, and you will not believe until you love one another.",
    grade: "Sahih",
    chapter: "Righteousness and Maintaining Ties of Kinship",
    reference: "Sahih Muslim 54",
  },
  {
    id: "muslim-2612",
    collectionId: "muslim",
    bookNumber: 45,
    hadithNumber: 2612,
    narrator: "Jabir (RA)",
    textArabic: "اتَّقُوا الظُّلْمَ فَإِنَّ الظُّلْمَ ظُلُمَاتٌ يَوْمَ الْقِيَامَةِ، وَاتَّقُوا الشُّحَّ فَإِنَّ الشُّحَّ أَهْلَكَ مَنْ كَانَ قَبْلَكُمْ",
    textEnglish: "Beware of oppression, for oppression will be darkness on the Day of Resurrection. Beware of stinginess, for stinginess destroyed those who came before you.",
    grade: "Sahih",
    chapter: "Righteousness and Maintaining Ties of Kinship",
    reference: "Sahih Muslim 2578",
  },
  {
    id: "muslim-2985",
    collectionId: "muslim",
    bookNumber: 54,
    hadithNumber: 2985,
    narrator: "Abu Hurairah (RA)",
    textArabic: "إِذَا مَاتَ الإِنْسَانُ انْقَطَعَ عَمَلُهُ إِلاَّ مِنْ ثَلاَثَةٍ: صَدَقَةٍ جَارِيَةٍ، أَوْ عِلْمٍ يُنْتَفَعُ بِهِ، أَوْ وَلَدٍ صَالِحٍ يَدْعُو لَهُ",
    textEnglish: "When a person dies, his deeds come to an end except for three: ongoing charity (Sadaqah Jariyah), beneficial knowledge, or a righteous child who prays for him.",
    grade: "Sahih",
    chapter: "Bequests",
    reference: "Sahih Muslim 1631",
  },
  {
    id: "muslim-1337",
    collectionId: "muslim",
    bookNumber: 15,
    hadithNumber: 1337,
    narrator: "Aisha (RA)",
    textArabic: "مَنْ أَحْدَثَ فِي أَمْرِنَا هَذَا مَا لَيْسَ مِنْهُ فَهُوَ رَدٌّ",
    textEnglish: "Whoever introduces into this matter of ours something that is not part of it will have it rejected.",
    grade: "Sahih",
    chapter: "Judicial Decisions",
    reference: "Sahih Muslim 1718",
  },
  {
    id: "muslim-2742b",
    collectionId: "muslim",
    bookNumber: 48,
    hadithNumber: 2742,
    narrator: "Abu Hurairah (RA)",
    textArabic: "إِنَّ اللَّهَ يَبْسُطُ يَدَهُ بِاللَّيْلِ لِيَتُوبَ مُسِيءُ النَّهَارِ، وَيَبْسُطُ يَدَهُ بِالنَّهَارِ لِيَتُوبَ مُسِيءُ اللَّيْلِ",
    textEnglish: "Verily, Allah stretches out His Hand at night to accept the repentance of the one who sinned during the day, and He stretches out His Hand during the day to accept the repentance of the one who sinned at night.",
    grade: "Sahih",
    chapter: "Repentance",
    reference: "Sahih Muslim 2759",
  },
  {
    id: "muslim-225",
    collectionId: "muslim",
    bookNumber: 2,
    hadithNumber: 225,
    narrator: "Uthman ibn Affan (RA)",
    textArabic: "مَنْ تَوَضَّأَ فَأَحْسَنَ الْوُضُوءَ خَرَجَتْ خَطَايَاهُ مِنْ جَسَدِهِ حَتَّى تَخْرُجَ مِنْ تَحْتِ أَظْفَارِهِ",
    textEnglish: "Whoever performs ablution properly, his sins will depart from his body, even from under his fingernails.",
    grade: "Sahih",
    chapter: "Purification",
    reference: "Sahih Muslim 245",
  },
  {
    id: "muslim-2674",
    collectionId: "muslim",
    bookNumber: 47,
    hadithNumber: 2674,
    narrator: "Abu Hurairah (RA)",
    textArabic: "الدُّعَاءُ سِلاَحُ الْمُؤْمِنِ وَعِمَادُ الدِّينِ وَنُورُ السَّمَاوَاتِ وَالأَرْضِ",
    textEnglish: "Supplication is the weapon of the believer, the pillar of the religion, and the light of the heavens and the earth.",
    grade: "Hasan",
    chapter: "Remembrance of Allah",
    reference: "Al-Mustadrak 1/492",
  },
];

// Part 2: Remaining 4 collections
import {
  abuDawudHadiths,
  tirmidhiHadiths,
  nasaiHadiths,
  ibnMajahHadiths,
} from "./hadith-data-part2";

// ============================================================================
// MAIN SEED FUNCTION
// ============================================================================

async function seedHadiths() {
  console.log("🌱 Starting hadith seed...\n");

  try {
    // Step 1: Insert collections
    console.log("📚 Inserting hadith collections...");
    for (const collection of collectionsData) {
      await db.insert(hadithCollections).values(collection).onConflictDoNothing();
      console.log(`  ✓ ${collection.name}`);
    }
    console.log(`\n✅ Inserted ${collectionsData.length} hadith collections\n`);

    // Step 2: Insert hadiths
    console.log("📖 Inserting hadiths...");
    const allHadiths = [
      ...bukhariHadiths,
      ...muslimHadiths,
      ...abuDawudHadiths,
      ...tirmidhiHadiths,
      ...nasaiHadiths,
      ...ibnMajahHadiths,
    ];
    let count = 0;
    for (const hadith of allHadiths) {
      await db.insert(hadiths).values(hadith).onConflictDoNothing();
      count++;
      if (count % 25 === 0) {
        console.log(`  ✓ Inserted ${count}/${allHadiths.length} hadiths`);
      }
    }
    console.log(`\n✅ Inserted ${allHadiths.length} hadiths\n`);

    // Step 3: Summary
    console.log("📊 Summary:");
    console.log(`  • ${collectionsData.length} collections (Kutub al-Sittah)`);
    console.log(`  • ${bukhariHadiths.length} Sahih al-Bukhari`);
    console.log(`  • ${muslimHadiths.length} Sahih Muslim`);
    console.log(`  • ${abuDawudHadiths.length} Sunan Abu Dawud`);
    console.log(`  • ${tirmidhiHadiths.length} Jami at-Tirmidhi`);
    console.log(`  • ${nasaiHadiths.length} Sunan an-Nasa'i`);
    console.log(`  • ${ibnMajahHadiths.length} Sunan Ibn Majah`);
    console.log(`  • Total: ${allHadiths.length} hadiths`);
    console.log("\n✨ Hadith seed completed successfully!");
  } catch (error) {
    console.error("\n❌ Error seeding hadiths:", error);
    throw error;
  } finally {
    await pool.end();
  }
}

// Run the seed script
seedHadiths().catch((error) => {
  console.error("Fatal error:", error);
  process.exit(1);
});
